export interface DefinitionEntry {
  term: string;
  /** Plain-language definition. May include inline `$...$` math. */
  definition: string;
  /** A concrete worked example. May include inline `$...$` math. */
  example?: string;
  /** Optional labeled diagram (see ShapeDiagram.tsx) drawn under the
   *  definition — e.g. "sector", "right-triangle", "cone". */
  diagram?: string;
}

export interface DefinitionTopic {
  key: string;
  navLabel: string;
  title: string;
  description: string;
  definitions: DefinitionEntry[];
}

export const DEFINITION_TOPICS: DefinitionTopic[] = [
  {
    key: "derivative",
    navLabel: "Derivatives",
    title: "Derivative Definitions",
    description: "Core vocabulary for differentiation, used throughout the Derivative calculator.",
    definitions: [
      { term: "Derivative", definition: "The instantaneous rate of change of a function — equivalently, the slope of the tangent line to its graph at a point.", example: "For $f(x) = x^2$, the derivative $f'(x) = 2x$ gives the slope at any $x$; at $x=3$ the slope is $6$." },
      { term: "Differentiable", definition: "A function is differentiable at a point if its derivative exists there (the graph has a well-defined, non-vertical tangent line, with no sharp corner or break).", example: "$f(x) = |x|$ is NOT differentiable at $x=0$ — it has a sharp corner there." },
      { term: "Higher-Order Derivative", definition: "The derivative of a derivative. The 2nd derivative $f''(x)$ measures how the slope itself is changing (concavity); the 3rd, 4th, etc. continue the pattern.", example: "For $f(x)=x^3$: $f'(x)=3x^2$, $f''(x)=6x$, $f'''(x)=6$." },
      { term: "Critical Point", definition: "A point where $f'(x) = 0$ or $f'(x)$ is undefined — a candidate location for a local maximum, local minimum, or neither.", example: "For $f(x)=x^2-4x$, $f'(x)=2x-4=0$ at $x=2$ — a critical point (here, a minimum)." },
      { term: "Local Maximum / Minimum", definition: "A point where a function's value is higher (or lower) than all nearby points — found by checking where $f'$ changes sign at a critical point.", example: "$f(x)=-x^2$ has a local maximum at $x=0$, since $f'$ goes from positive to negative there." },
      { term: "Concavity", definition: "Whether a curve bends upward (concave up, $f''>0$) or downward (concave down, $f''<0$).", example: "$f(x)=x^2$ has $f''(x)=2>0$ everywhere, so it's concave up everywhere (a familiar upward-opening parabola)." },
      { term: "Inflection Point", definition: "A point where a curve changes concavity — from concave up to concave down, or vice versa (where $f''$ changes sign).", example: "$f(x)=x^3$ has $f''(x)=6x$, which changes sign at $x=0$ — an inflection point." },
      { term: "Chain Rule (concept)", definition: "The rule for differentiating a composition of functions (a \"function of a function\") — differentiate the outer function, then multiply by the derivative of the inner function.", example: "For $f(x)=\\sin(3x)$: outer $\\sin(u)$, inner $u=3x$, so $f'(x)=\\cos(3x)\\cdot 3$." },
      { term: "Tangent Line", definition: "The straight line that just touches a curve at a point and has the same slope as the curve there — its slope IS the derivative at that point.", example: "For $f(x)=x^2$ at $x=1$: slope $=2$, so the tangent line is $y = 2x - 1$." },
      { term: "Secant Line", definition: "A line through two points on a curve. Its slope is the AVERAGE rate of change; letting the two points slide together turns it into the tangent line.", example: "For $f(x)=x^2$ between $x=1$ and $x=3$: slope $=\\frac{9-1}{3-1}=4$." },
      { term: "Difference Quotient", definition: "The formal definition of the derivative as a limit: $f'(x)=\\lim_{h\\to0}\\frac{f(x+h)-f(x)}{h}$ — the slope of a secant line as its two points merge.", example: "For $f(x)=x^2$: $\\frac{(x+h)^2-x^2}{h}=2x+h \\to 2x$ as $h\\to0$." },
      { term: "Product Rule", definition: "To differentiate a product of two functions: $\\left(uv\\right)' = u'v + uv'$ — differentiate each factor in turn, keeping the other unchanged.", example: "$\\frac{d}{dx}[x^2\\sin x] = 2x\\sin x + x^2\\cos x$." },
      { term: "Quotient Rule", definition: "To differentiate a fraction of two functions: $\\left(\\frac{u}{v}\\right)' = \\frac{u'v-uv'}{v^2}$ — note the order matters, unlike the product rule.", example: "$\\frac{d}{dx}\\left[\\frac{x}{x+1}\\right] = \\frac{1(x+1)-x(1)}{(x+1)^2} = \\frac{1}{(x+1)^2}$." },
      { term: "Implicit Differentiation", definition: "Differentiating an equation that isn't solved for $y$, by treating $y$ as a function of $x$ and applying the chain rule to every $y$ term.", example: "From $x^2+y^2=25$: $2x+2y\\frac{dy}{dx}=0$, so $\\frac{dy}{dx} = -\\frac{x}{y}$." },
      { term: "Logarithmic Differentiation", definition: "Taking $\\ln$ of both sides before differentiating — turns messy products, quotients, and variable exponents into simple sums.", example: "For $y = x^x$: $\\ln y = x\\ln x$, so $\\frac{y'}{y} = \\ln x + 1$ and $y' = x^x(\\ln x + 1)$." },
      { term: "Related Rates", definition: "Problems where two or more quantities change together over time — differentiate the equation relating them with respect to $t$.", example: "If $A=\\pi r^2$, then $\\frac{dA}{dt} = 2\\pi r\\frac{dr}{dt}$." },
      { term: "Mean Value Theorem", definition: "If $f$ is continuous on $[a,b]$ and differentiable on $(a,b)$, there is at least one point $c$ inside where the instantaneous slope equals the average slope: $f'(c)=\\frac{f(b)-f(a)}{b-a}$.", example: "Driving 120 km in 2 hours means at some instant your speedometer read exactly 60 km/h." },
      { term: "Rolle's Theorem", definition: "The special case of the Mean Value Theorem where $f(a)=f(b)$ — then there must be a point $c$ inside with $f'(c)=0$ (a flat spot).", example: "$f(x)=x^2-4$ has $f(-2)=f(2)=0$, and indeed $f'(0)=0$." },
      { term: "Linear Approximation", definition: "Using the tangent line at a nearby easy point to estimate a function's value: $f(x)\\approx f(a)+f'(a)(x-a)$.", example: "$\\sqrt{4.1}\\approx 2 + \\frac{1}{4}(0.1) = 2.025$ (true value $\\approx2.0248$)." },
      { term: "Second Derivative Test", definition: "At a critical point $c$: if $f''(c)>0$ it's a local minimum; if $f''(c)<0$ a local maximum; if $f''(c)=0$ the test is inconclusive and you fall back to the sign of $f'$.", example: "$f(x)=x^2-4x$ has $f'(2)=0$ and $f''(2)=2>0$ — a local minimum." },
      { term: "Increasing / Decreasing", definition: "A function is increasing wherever $f'(x)>0$ and decreasing wherever $f'(x)<0$ — the sign of the derivative reads directly as the direction of the graph.", example: "$f(x)=x^3-3x$ has $f'(x)=3x^2-3<0$ on $(-1,1)$, so it decreases there." },
      { term: "Partial Derivative", definition: "The derivative of a multivariable function with respect to ONE variable, treating all the others as constants, written $\\frac{\\partial f}{\\partial x}$.", example: "For $f(x,y)=x^2y$: $\\frac{\\partial f}{\\partial x} = 2xy$ and $\\frac{\\partial f}{\\partial y} = x^2$." },
    ],
  },
  {
    key: "integration",
    navLabel: "Integrals",
    title: "Integration Definitions",
    description: "Core vocabulary for integration, used throughout the Integration calculator.",
    definitions: [
      { term: "Antiderivative", definition: "A function $F(x)$ whose derivative equals a given function $f(x)$ — i.e. $F'(x) = f(x)$. Antiderivatives aren't unique: any two differ only by a constant.", example: "$F(x) = x^2$ is an antiderivative of $f(x) = 2x$, since $\\frac{d}{dx}[x^2] = 2x$." },
      { term: "Indefinite Integral", definition: "The general family of all antiderivatives of a function, written $\\int f(x)\\,dx$ and always including \"$+ C$\" for an arbitrary constant.", example: "$\\int 2x\\,dx = x^2 + C$ — every value of $C$ gives a valid antiderivative." },
      { term: "Definite Integral", definition: "The signed area between a curve and the x-axis over a specific interval $[a,b]$, written $\\int_a^b f(x)\\,dx$ — a single number, not a family of functions.", example: "$\\int_0^2 x\\,dx = 2$ — the area of the triangle under the line $y=x$ from $0$ to $2$." },
      { term: "Constant of Integration (C)", definition: "The \"+C\" added to every indefinite integral, representing that infinitely many antiderivatives exist (any constant added to one still has the same derivative).", example: "Both $x^2+1$ and $x^2-5$ have derivative $2x$ — both are captured by $x^2+C$." },
      { term: "Riemann Sum", definition: "An approximation of the area under a curve by summing the areas of many thin rectangles — the idea a definite integral makes exact as the rectangles become infinitely thin.", example: "Approximating $\\int_0^1 x^2\\,dx$ with 4 rectangles of width $0.25$ each." },
      { term: "Area Under a Curve", definition: "The region enclosed between a function's graph and the x-axis over an interval — computed exactly using a definite integral.", example: "The area under $f(x)=x^2$ from $x=0$ to $x=3$ is $\\int_0^3 x^2\\,dx = 9$." },
      { term: "Fundamental Theorem of Calculus", definition: "The theorem connecting derivatives and integrals: it says differentiation and integration are reverse processes of each other, and gives the shortcut $\\int_a^b f(x)\\,dx = F(b)-F(a)$.", example: "For $f(x)=x$: $F(x)=\\frac{x^2}{2}$, so $\\int_1^3 x\\,dx = F(3)-F(1) = 4.5-0.5=4$." },
      { term: "u-Substitution", definition: "The reverse of the chain rule: replace an inner function with $u$, swap $dx$ for $du$, integrate in $u$, then substitute back.", example: "$\\int 2x\\cos(x^2)\\,dx$ with $u=x^2$, $du=2x\\,dx$ becomes $\\int\\cos u\\,du = \\sin(x^2)+C$." },
      { term: "Integration by Parts", definition: "The reverse of the product rule: $\\int u\\,dv = uv - \\int v\\,du$ — useful when a product mixes an easy-to-differentiate factor with an easy-to-integrate one.", example: "$\\int x e^x dx$ with $u=x$, $dv=e^x dx$ gives $xe^x - e^x + C$." },
      { term: "Partial Fractions", definition: "Splitting a rational function into a sum of simpler fractions so each piece integrates with a basic rule.", example: "$\\frac{1}{x(x+1)} = \\frac{1}{x}-\\frac{1}{x+1}$, so the integral is $\\ln|x|-\\ln|x+1|+C$." },
      { term: "Improper Integral", definition: "An integral with an infinite limit, or with an integrand that blows up inside the interval — defined as a limit, and said to converge if that limit is finite.", example: "$\\int_1^\\infty \\frac{1}{x^2}dx = \\lim_{b\\to\\infty}\\left[-\\frac{1}{x}\\right]_1^b = 1$ (converges)." },
      { term: "Area Between Curves", definition: "The area enclosed between two graphs over $[a,b]$: integrate the upper curve minus the lower curve, $\\int_a^b (f-g)\\,dx$.", example: "Between $y=x$ and $y=x^2$ from $0$ to $1$: $\\int_0^1 (x-x^2)dx = \\frac{1}{6}$." },
      { term: "Average Value of a Function", definition: "The height of the rectangle with the same area as the region under the curve: $f_{\\text{avg}} = \\frac{1}{b-a}\\int_a^b f(x)\\,dx$.", example: "The average of $f(x)=x^2$ on $[0,3]$ is $\\frac{1}{3}\\int_0^3x^2dx = 3$." },
      { term: "Volume of Revolution (Disk Method)", definition: "Spinning a region about an axis sweeps out a solid; slicing it into thin disks gives $V=\\pi\\int_a^b [f(x)]^2dx$.", example: "Rotating $y=x$ on $[0,1]$ about the x-axis gives $V=\\pi\\int_0^1x^2dx = \\frac{\\pi}{3}$." },
      { term: "Arc Length", definition: "The true length of a curve (not its horizontal span): $L=\\int_a^b\\sqrt{1+[f'(x)]^2}\\,dx$.", example: "For a straight line $f(x)=x$ on $[0,1]$: $L=\\int_0^1\\sqrt2\\,dx = \\sqrt2$ — the diagonal, as expected." },
      { term: "Trapezoidal Rule", definition: "A numerical estimate of a definite integral that joins sample points with straight lines instead of flat tops: $\\int_a^b f \\approx \\frac{h}{2}[f_0+2f_1+\\dots+2f_{n-1}+f_n]$.", example: "With 2 strips of width $0.5$, $\\int_0^1x^2dx \\approx 0.375$ (exact: $0.333$)." },
      { term: "Simpson's Rule", definition: "A more accurate numerical rule that fits parabolas through triples of points: $\\frac{h}{3}[f_0+4f_1+2f_2+\\dots+4f_{n-1}+f_n]$, with $n$ even.", example: "Simpson's rule integrates any cubic exactly, using just a handful of points." },
      { term: "Definite Integral Properties", definition: "Reversing limits flips the sign, $\\int_a^b = -\\int_b^a$; equal limits give zero; and intervals split additively, $\\int_a^c = \\int_a^b + \\int_b^c$.", example: "$\\int_0^2 f + \\int_2^5 f = \\int_0^5 f$." },
      { term: "Double Integral", definition: "An integral over a two-dimensional region, computed as an inner integral followed by an outer one — it gives the volume under a surface $z=f(x,y)$.", example: "$\\int_0^1\\int_0^1 xy\\,dx\\,dy = \\frac{1}{4}$." },
    ],
  },
  {
    key: "limits",
    navLabel: "Limits",
    title: "Limit Definitions",
    description: "Core vocabulary for limits and continuity, used in the Limits calculator.",
    definitions: [
      { term: "Limit", definition: "The value a function approaches as its input gets arbitrarily close to some point — regardless of whether the function is actually defined at that exact point.", example: "$\\lim_{x\\to 2}(x+3) = 5$, even though this just means \"as $x$ nears $2$\"." },
      { term: "One-Sided Limit", definition: "The value a function approaches from only the left ($x\\to a^-$) or only the right ($x\\to a^+$) — useful when a function behaves differently on each side.", example: "For $f(x)=\\frac{|x|}{x}$: $\\lim_{x\\to 0^-}f(x)=-1$ but $\\lim_{x\\to 0^+}f(x)=1$." },
      { term: "Two-Sided Limit Exists", definition: "A two-sided limit exists exactly when both one-sided limits exist AND agree with each other.", example: "Since the left/right limits of $\\frac{|x|}{x}$ at $0$ disagree ($-1$ vs $1$), the two-sided limit does not exist." },
      { term: "Continuity", definition: "A function is continuous at a point if the limit there exists AND equals the function's actual value at that point (no gaps, jumps, or holes).", example: "$f(x)=x^2$ is continuous everywhere: $\\lim_{x\\to a}f(x) = f(a)$ for every $a$." },
      { term: "Discontinuity", definition: "A point where a function fails to be continuous — the limit doesn't exist, or doesn't match the function's actual value there.", example: "$f(x)=\\frac{1}{x}$ has a discontinuity at $x=0$, where the function is undefined." },
      { term: "Removable Discontinuity", definition: "A \"hole\" in a graph where the limit exists, but either the function isn't defined there or its actual value doesn't match the limit — it could be \"fixed\" by redefining just that one point.", example: "$f(x)=\\frac{x^2-1}{x-1}$ has a removable discontinuity at $x=1$ (it simplifies to $x+1$ everywhere else)." },
      { term: "Vertical Asymptote", definition: "A vertical line $x=a$ that a function's graph approaches but never reaches, where the function's values grow without bound (the limit is $+\\infty$ or $-\\infty$).", example: "$f(x)=\\frac{1}{x}$ has a vertical asymptote at $x=0$." },
      { term: "Horizontal Asymptote", definition: "A horizontal line $y=L$ that a function's graph approaches as $x\\to\\infty$ or $x\\to-\\infty$.", example: "$f(x)=\\frac{1}{x}$ has a horizontal asymptote at $y=0$, since $\\lim_{x\\to\\infty}\\frac{1}{x}=0$." },
      { term: "Indeterminate Form", definition: "An expression like $\\frac{0}{0}$, $\\frac{\\infty}{\\infty}$, $0\\cdot\\infty$, or $\\infty-\\infty$ that a limit can produce — it carries no information on its own, so the expression must be rewritten or L'Hôpital's rule applied.", example: "$\\lim_{x\\to0}\\frac{\\sin x}{x}$ is $\\frac{0}{0}$ at first glance, but the true limit is $1$." },
      { term: "L'Hôpital's Rule", definition: "If a limit gives $\\frac{0}{0}$ or $\\frac{\\infty}{\\infty}$, the limit of the ratio equals the limit of the ratio of the DERIVATIVES: $\\lim\\frac{f}{g}=\\lim\\frac{f'}{g'}$.", example: "$\\lim_{x\\to0}\\frac{\\sin x}{x} = \\lim_{x\\to0}\\frac{\\cos x}{1} = 1$." },
      { term: "Squeeze Theorem", definition: "If $g(x)\\le f(x)\\le h(x)$ near a point and the outer two functions share the same limit $L$ there, then $f$ is trapped and must also approach $L$.", example: "Since $-x^2\\le x^2\\sin\\frac{1}{x}\\le x^2$, the middle limit at $0$ is $0$." },
      { term: "Limit at Infinity", definition: "The value a function settles toward as $x$ grows without bound — this is what identifies horizontal asymptotes.", example: "$\\lim_{x\\to\\infty}\\frac{3x^2+1}{x^2-5} = 3$ (compare leading coefficients)." },
      { term: "Jump Discontinuity", definition: "A break where both one-sided limits exist but differ, so the graph leaps from one value to another.", example: "A step function jumping from $0$ to $1$ at $x=0$." },
      { term: "Infinite Discontinuity", definition: "A break where the function's values grow without bound on at least one side — this is the discontinuity at a vertical asymptote.", example: "$f(x)=\\frac{1}{x^2}$ at $x=0$." },
      { term: "Epsilon-Delta Definition", definition: "The formal meaning of $\\lim_{x\\to a}f(x)=L$: for every tolerance $\\varepsilon>0$ there is a closeness $\\delta>0$ such that $0<|x-a|<\\delta$ forces $|f(x)-L|<\\varepsilon$.", example: "It makes \"gets arbitrarily close\" precise: you name the tolerance, the limit meets it." },
      { term: "Oblique (Slant) Asymptote", definition: "A slanted line a graph approaches at infinity — it appears when a rational function's numerator degree is exactly one higher than its denominator's.", example: "$f(x)=\\frac{x^2+1}{x}$ approaches the line $y=x$." },
      { term: "Intermediate Value Theorem", definition: "A function continuous on $[a,b]$ takes every value between $f(a)$ and $f(b)$ somewhere in between — the basis for root-finding by sign change.", example: "$f(x)=x^3-x-1$ has $f(1)<0$ and $f(2)>0$, so a root lies in $(1,2)$." },
    ],
  },
  {
    key: "equations",
    navLabel: "Equations",
    title: "Equation Definitions",
    description: "Core vocabulary for equations, used in the Equation Solver.",
    definitions: [
      { term: "Linear Equation", definition: "An equation where the variable appears only to the first power — its graph is a straight line.", example: "$3x + 5 = 20$ is linear; solving gives $x=5$." },
      { term: "Quadratic Equation", definition: "An equation where the variable's highest power is 2, of the standard form $ax^2+bx+c=0$ — its graph is a parabola.", example: "$x^2 - 5x + 6 = 0$ is quadratic; it factors as $(x-2)(x-3)=0$." },
      { term: "Root (Solution)", definition: "A value of the variable that makes the equation true — where the corresponding graph crosses the x-axis.", example: "$x=2$ and $x=3$ are the roots of $x^2-5x+6=0$." },
      { term: "Discriminant", definition: "The expression $b^2-4ac$ inside a quadratic's square root — its sign tells you how many real solutions exist before you even solve.", example: "For $x^2-5x+6=0$: $D=25-24=1>0$, so there are two distinct real roots." },
      { term: "Coefficient", definition: "The numeric multiplier in front of a variable term.", example: "In $3x^2 - 5x + 6$, the coefficients are $3$, $-5$, and the constant term $6$." },
      { term: "Vertex", definition: "The highest or lowest point of a parabola — where a quadratic function reaches its maximum or minimum value.", example: "$f(x)=x^2-4x+3$ has its vertex at $x=2$ (found via $-b/2a$), where $f(2)=-1$." },
      { term: "Polynomial Equation", definition: "An equation built only from powers of the variable with whole-number exponents, multiplied by coefficients and added together.", example: "$2x^3-4x^2+x-7=0$ is a polynomial equation of degree 3." },
      { term: "Degree", definition: "The highest power of the variable appearing in a polynomial — it caps the number of roots the equation can have.", example: "$x^4-1=0$ has degree 4, so at most 4 roots (here $\\pm1,\\pm i$)." },
      { term: "Completing the Square", definition: "Rewriting $ax^2+bx+c$ as $a(x+h)^2+k$ — this exposes the vertex directly and is how the quadratic formula is derived.", example: "$x^2+6x+5 = (x+3)^2-4$, so the vertex is $(-3,-4)$." },
      { term: "Factoring", definition: "Writing an expression as a product of simpler factors, so the zero-product rule turns one equation into several easy ones.", example: "$x^2-5x+6=(x-2)(x-3)$, giving $x=2$ or $x=3$." },
      { term: "System of Equations", definition: "Two or more equations that must hold simultaneously — a solution is a set of values satisfying all of them at once.", example: "$x+y=5$ and $x-y=1$ give $x=3$, $y=2$." },
      { term: "Consistent / Inconsistent System", definition: "A system is consistent if at least one solution exists, and inconsistent if none does (the equations contradict each other).", example: "$x+y=2$ with $x+y=5$ is inconsistent — parallel lines that never meet." },
      { term: "Extraneous Solution", definition: "A value that appears while solving (usually after squaring both sides or clearing denominators) but fails in the ORIGINAL equation — always check back.", example: "Squaring $\\sqrt{x}=-2$ suggests $x=4$, but $\\sqrt4=2\\neq-2$, so it's extraneous." },
      { term: "Sum and Product of Roots (Vieta)", definition: "For $ax^2+bx+c=0$ with roots $p,q$: $p+q=-\\frac{b}{a}$ and $pq=\\frac{c}{a}$ — root facts without solving.", example: "For $x^2-5x+6=0$: sum $=5$, product $=6$ (roots $2$ and $3$)." },
      { term: "Axis of Symmetry", definition: "The vertical line $x=-\\frac{b}{2a}$ that splits a parabola into mirror halves, passing through its vertex.", example: "For $f(x)=x^2-4x+3$, the axis of symmetry is $x=2$." },
      { term: "Inequality", definition: "A statement comparing two expressions with $<$, $\\le$, $>$, or $\\ge$. Its solution is usually an interval, and multiplying by a negative flips the sign.", example: "$-2x>6$ gives $x<-3$, not $x>-3$." },
    ],
  },
  {
    key: "matrix",
    navLabel: "Matrices",
    title: "Types of Matrices",
    description: "Common matrix types and terminology, used in the Matrix calculator.",
    definitions: [
      { term: "Matrix", definition: "A rectangular grid of numbers arranged in rows and columns, used to represent linear systems, transformations, and data.", example: "$\\begin{bmatrix}1&2\\\\3&4\\end{bmatrix}$ is a 2×2 matrix, and $\\begin{bmatrix}1&2&3\\\\4&5&6\\\\7&8&9\\end{bmatrix}$ is a 3×3 matrix." },
      { term: "Row Matrix", definition: "A matrix with exactly one row.", example: "$\\begin{bmatrix}1&2&3\\end{bmatrix}$ is a 1×3 row matrix." },
      { term: "Column Matrix", definition: "A matrix with exactly one column.", example: "$\\begin{bmatrix}1\\\\2\\\\3\\end{bmatrix}$ is a 3×1 column matrix." },
      { term: "Square Matrix", definition: "A matrix with the same number of rows and columns.", example: "$\\begin{bmatrix}1&2\\\\3&4\\end{bmatrix}$ is a 2×2 square matrix, and $\\begin{bmatrix}1&0&2\\\\0&3&1\\\\4&1&5\\end{bmatrix}$ is a 3×3 square matrix." },
      { term: "Zero (Null) Matrix", definition: "A matrix in which every entry is $0$.", example: "$\\begin{bmatrix}0&0\\\\0&0\\end{bmatrix}$ is a 2×2 zero matrix, and $\\begin{bmatrix}0&0&0\\\\0&0&0\\\\0&0&0\\end{bmatrix}$ is a 3×3 zero matrix." },
      { term: "Identity Matrix", definition: "A square matrix with $1$s on the main diagonal and $0$s everywhere else — the matrix equivalent of the number $1$ ($AI=A$).", example: "$I_2 = \\begin{bmatrix}1&0\\\\0&1\\end{bmatrix}$ and $I_3 = \\begin{bmatrix}1&0&0\\\\0&1&0\\\\0&0&1\\end{bmatrix}$ are the 2×2 and 3×3 identity matrices." },
      { term: "Diagonal Matrix", definition: "A square matrix where every entry OFF the main diagonal is $0$ (diagonal entries can be anything).", example: "$\\begin{bmatrix}5&0\\\\0&-2\\end{bmatrix}$ is a 2×2 diagonal matrix, and $\\begin{bmatrix}3&0&0\\\\0&-1&0\\\\0&0&7\\end{bmatrix}$ is a 3×3 diagonal matrix." },
      { term: "Scalar Matrix", definition: "A diagonal matrix where every diagonal entry is the SAME number.", example: "$\\begin{bmatrix}4&0\\\\0&4\\end{bmatrix}$ is a 2×2 scalar matrix, and $\\begin{bmatrix}2&0&0\\\\0&2&0\\\\0&0&2\\end{bmatrix}$ is a 3×3 scalar matrix." },
      { term: "Symmetric Matrix", definition: "A square matrix that equals its own transpose ($A = A^T$) — it's a mirror image of itself across the main diagonal (entry $(i,j)$ always equals entry $(j,i)$).", example: "$\\begin{bmatrix}1&2\\\\2&5\\end{bmatrix}$ is symmetric, and so is $\\begin{bmatrix}1&2&3\\\\2&4&5\\\\3&5&6\\end{bmatrix}$ — every entry above the diagonal matches its mirror below it." },
      { term: "Skew-Symmetric Matrix", definition: "A square matrix that equals the NEGATIVE of its own transpose ($A^T = -A$) — every diagonal entry must be $0$, and entry $(j,i)$ is always the negative of entry $(i,j)$.", example: "$\\begin{bmatrix}0&2\\\\-2&0\\end{bmatrix}$ is skew-symmetric, and so is $\\begin{bmatrix}0&2&-1\\\\-2&0&3\\\\1&-3&0\\end{bmatrix}$." },
      { term: "Upper Triangular Matrix", definition: "A square matrix where every entry BELOW the main diagonal is $0$.", example: "$\\begin{bmatrix}1&2\\\\0&4\\end{bmatrix}$ is upper triangular, and so is $\\begin{bmatrix}1&2&3\\\\0&4&5\\\\0&0&6\\end{bmatrix}$." },
      { term: "Lower Triangular Matrix", definition: "A square matrix where every entry ABOVE the main diagonal is $0$.", example: "$\\begin{bmatrix}1&0\\\\3&4\\end{bmatrix}$ is lower triangular, and so is $\\begin{bmatrix}1&0&0\\\\2&3&0\\\\4&5&6\\end{bmatrix}$." },
      { term: "Singular Matrix", definition: "A square matrix whose determinant is $0$ — it has no inverse.", example: "$\\begin{bmatrix}1&2\\\\2&4\\end{bmatrix}$ is singular, since $\\det = 1(4)-2(2) = 0$. $\\begin{bmatrix}1&2&3\\\\2&4&6\\\\1&0&1\\end{bmatrix}$ is also singular, since its 2nd row is exactly twice its 1st row." },
      { term: "Non-Singular Matrix", definition: "A square matrix whose determinant is NOT $0$ — it has a valid inverse.", example: "$\\begin{bmatrix}1&2\\\\3&4\\end{bmatrix}$ is non-singular, since $\\det = -2 \\neq 0$." },
      { term: "Transpose", definition: "The matrix formed by flipping a matrix over its main diagonal — rows become columns and columns become rows.", example: "The transpose of $\\begin{bmatrix}1&2\\\\3&4\\end{bmatrix}$ is $\\begin{bmatrix}1&3\\\\2&4\\end{bmatrix}$." },
      { term: "Elementary Matrix", definition: "An identity matrix with exactly ONE elementary row operation applied to it (a single row swap, a single row scaled, or one row added to another) — multiplying by an elementary matrix has the same effect as performing that row operation directly.", example: "$\\begin{bmatrix}1&0\\\\0&2\\end{bmatrix}$ is the elementary matrix that scales row 2 by $2$; $\\begin{bmatrix}0&1\\\\1&0\\end{bmatrix}$ is the elementary matrix that swaps rows 1 and 2." },
      { term: "Row Echelon Form (REF)", definition: "A matrix shape reached by Gaussian elimination: each row's first non-zero entry (its \"pivot\") sits further right than the pivot in the row above, and all entries below every pivot are $0$.", example: "$\\begin{bmatrix}1&2&3\\\\0&1&4\\\\0&0&1\\end{bmatrix}$ is in row echelon form — pivots are the 1's, stepping right down the diagonal." },
      { term: "Reduced Row Echelon Form (RREF)", definition: "Row echelon form taken one step further: every pivot equals $1$, and every entry ABOVE each pivot is also $0$ (not just below it) — this is the most simplified form a matrix can be row-reduced to.", example: "$\\begin{bmatrix}1&0&0\\\\0&1&0\\\\0&0&1\\end{bmatrix}$ is in reduced row echelon form (here it's simply the identity matrix)." },
      { term: "Rank", definition: "The number of non-zero rows remaining once a matrix is reduced to row echelon form — informally, how many of its rows carry genuinely independent information.", example: "$\\begin{bmatrix}1&2\\\\2&4\\end{bmatrix}$ has rank $1$ (row 2 is just row 1 doubled, so it reduces away to a zero row)." },
      { term: "Order (Dimension)", definition: "The size of a matrix, written rows × columns — always rows first.", example: "$\\begin{bmatrix}1&2&3\\\\4&5&6\\end{bmatrix}$ has order $2\\times3$." },
      { term: "Conformable for Multiplication", definition: "$AB$ is only defined when the number of COLUMNS of $A$ equals the number of ROWS of $B$; the product then has $A$'s rows and $B$'s columns.", example: "A $2\\times3$ times a $3\\times4$ gives a $2\\times4$; the reverse order is undefined." },
      { term: "Trace", definition: "The sum of the entries on the main diagonal of a square matrix.", example: "$\\text{tr}\\begin{bmatrix}1&2\\\\3&4\\end{bmatrix} = 1+4 = 5$." },
      { term: "Minor", definition: "The determinant of the smaller matrix left after deleting one entry's row and column.", example: "For $\\begin{bmatrix}1&2&3\\\\4&5&6\\\\7&8&9\\end{bmatrix}$, the minor $M_{11}=\\det\\begin{bmatrix}5&6\\\\8&9\\end{bmatrix}=-3$." },
      { term: "Cofactor", definition: "A minor with a sign attached by position: $C_{ij}=(-1)^{i+j}M_{ij}$ — the checkerboard of $+$ and $-$ used in expansion.", example: "$C_{12} = -M_{12}$, since $(-1)^{1+2}=-1$." },
      { term: "Adjugate (Adjoint)", definition: "The transpose of the matrix of cofactors — the key ingredient of the inverse formula $A^{-1}=\\frac{1}{\\det A}\\,\\text{adj}(A)$.", example: "For $\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}$, $\\text{adj}(A)=\\begin{bmatrix}d&-b\\\\-c&a\\end{bmatrix}$." },
      { term: "Inverse Matrix", definition: "The matrix $A^{-1}$ satisfying $AA^{-1}=A^{-1}A=I$. It exists only when $\\det A\\neq0$.", example: "$\\begin{bmatrix}2&0\\\\0&4\\end{bmatrix}^{-1} = \\begin{bmatrix}0.5&0\\\\0&0.25\\end{bmatrix}$." },
      { term: "Augmented Matrix", definition: "The coefficient matrix of a linear system with the constants attached as an extra column, separated by a bar — the object you row-reduce when solving.", example: "$x+2y=5$, $3x-y=1$ becomes $\\left[\\begin{array}{cc|c}1&2&5\\\\3&-1&1\\end{array}\\right]$." },
      { term: "Pivot", definition: "The leading non-zero entry of a row once the matrix is in echelon form — its column is a pivot column, and each pivot marks one independent equation.", example: "In $\\begin{bmatrix}1&2&3\\\\0&1&4\\\\0&0&0\\end{bmatrix}$ the pivots sit in columns 1 and 2, so the rank is 2." },
      { term: "Free Variable", definition: "A variable whose column has no pivot — it can take any value, so the system has infinitely many solutions.", example: "With 3 unknowns and rank 2, there is $3-2 = 1$ free variable." },
      { term: "Homogeneous System", definition: "A system $A\\mathbf{x}=\\mathbf{0}$ where every constant is zero. It is always consistent, since $\\mathbf{x}=\\mathbf{0}$ always works; non-zero solutions exist exactly when $\\det A = 0$.", example: "$2x+4y=0$, $x+2y=0$ has infinitely many solutions along $x=-2y$." },
      { term: "Cramer's Rule", definition: "Solving a square system by determinants: $x_i = \\frac{\\det A_i}{\\det A}$, where $A_i$ is $A$ with column $i$ replaced by the constants. Requires $\\det A\\neq0$.", example: "For a $2\\times2$ system, $x = \\frac{\\det A_x}{\\det A}$." },
      { term: "Orthogonal Matrix", definition: "A square matrix whose transpose is its inverse ($A^TA=I$) — its rows and columns are mutually perpendicular unit vectors, and $\\det A = \\pm1$.", example: "A rotation matrix $\\begin{bmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{bmatrix}$ is orthogonal." },
      { term: "Idempotent Matrix", definition: "A square matrix that stays the same when squared: $A^2=A$.", example: "$\\begin{bmatrix}1&0\\\\0&0\\end{bmatrix}$ is idempotent." },
      { term: "Nilpotent Matrix", definition: "A square matrix some power of which is the zero matrix: $A^k=0$ for some $k$.", example: "$\\begin{bmatrix}0&1\\\\0&0\\end{bmatrix}$ squares to the zero matrix." },
      { term: "Eigenvalue and Eigenvector", definition: "A non-zero vector $\\mathbf{v}$ with $A\\mathbf{v}=\\lambda\\mathbf{v}$ is an eigenvector — the matrix only stretches it by the factor $\\lambda$, its eigenvalue. Found from $\\det(A-\\lambda I)=0$.", example: "$\\begin{bmatrix}2&0\\\\0&3\\end{bmatrix}$ has eigenvalues $2$ and $3$ along the coordinate axes." },
    ],
  },
  {
    key: "complex",
    navLabel: "Complex Numbers",
    title: "Complex Number Definitions",
    description: "Core vocabulary for complex numbers, used in the Complex Number calculator.",
    definitions: [
      { term: "Complex Number", definition: "A number of the form $a+bi$, combining a real part $a$ and an imaginary part $b$ (multiplied by the imaginary unit $i$).", example: "$3+4i$ is a complex number with real part $3$ and imaginary part $4$." },
      { term: "Imaginary Unit (i)", definition: "The number defined so that $i^2=-1$ — it lets us take square roots of negative numbers.", example: "$\\sqrt{-9} = 3i$, since $(3i)^2 = 9i^2 = -9$." },
      { term: "Real Part", definition: "The non-imaginary component of a complex number $a+bi$ — just $a$.", example: "The real part of $5-2i$ is $5$." },
      { term: "Imaginary Part", definition: "The coefficient of $i$ in a complex number $a+bi$ — just $b$ (not $bi$).", example: "The imaginary part of $5-2i$ is $-2$." },
      { term: "Complex Conjugate", definition: "The complex number formed by flipping the sign of the imaginary part — $a+bi$ becomes $a-bi$.", example: "The conjugate of $3+4i$ is $3-4i$." },
      { term: "Modulus", definition: "The distance from the origin to a complex number on the complex plane — its \"size\", computed as $\\sqrt{a^2+b^2}$.", example: "$|3+4i| = \\sqrt{9+16} = 5$." },
      { term: "Argument", definition: "The angle a complex number makes with the positive real axis on the complex plane.", example: "The argument of $1+i$ is $45°$ (or $\\pi/4$ radians)." },
      { term: "Polar Form", definition: "Writing a complex number as $r(\\cos\\theta+i\\sin\\theta)$ using its modulus $r$ and argument $\\theta$, instead of $a+bi$.", example: "$1+i$ in polar form is $\\sqrt2(\\cos45°+i\\sin45°)$." },
      { term: "Argand Plane", definition: "The plane used to picture complex numbers: the horizontal axis holds the real part, the vertical axis the imaginary part.", example: "$3+4i$ is plotted at the point $(3,4)$." },
      { term: "Principal Argument", definition: "The argument of a complex number restricted to $(-\\pi,\\pi]$, so every number has exactly one standard angle.", example: "The principal argument of $-1$ is $\\pi$, not $3\\pi$." },
      { term: "Exponential (Euler) Form", definition: "Writing a complex number as $re^{i\\theta}$ using Euler's formula $e^{i\\theta}=\\cos\\theta+i\\sin\\theta$ — multiplication becomes adding angles.", example: "$1+i = \\sqrt2\\,e^{i\\pi/4}$." },
      { term: "De Moivre's Theorem", definition: "Raising a complex number in polar form to a power multiplies the angle: $[r(\\cos\\theta+i\\sin\\theta)]^n = r^n(\\cos n\\theta+i\\sin n\\theta)$.", example: "$(1+i)^4 = (\\sqrt2)^4(\\cos\\pi+i\\sin\\pi) = -4$." },
      { term: "Roots of Unity", definition: "The $n$ complex solutions of $z^n=1$, evenly spaced around the unit circle at angles $\\frac{2\\pi k}{n}$.", example: "The cube roots of unity are $1$, $-\\frac12+\\frac{\\sqrt3}{2}i$, and $-\\frac12-\\frac{\\sqrt3}{2}i$." },
      { term: "Purely Imaginary", definition: "A complex number whose real part is zero — it sits on the vertical axis of the Argand plane.", example: "$-7i$ is purely imaginary; $2-7i$ is not." },
      { term: "Equality of Complex Numbers", definition: "Two complex numbers are equal only when their real parts match AND their imaginary parts match — one complex equation carries two real ones.", example: "$a+bi = 3-2i$ forces $a=3$ and $b=-2$." },
      { term: "Division by the Conjugate", definition: "To divide complex numbers, multiply top and bottom by the denominator's conjugate — this makes the denominator real.", example: "$\\frac{1}{2+i} = \\frac{2-i}{(2+i)(2-i)} = \\frac{2-i}{5}$." },
      { term: "Powers of i", definition: "The powers of $i$ cycle with period 4: $i^1=i$, $i^2=-1$, $i^3=-i$, $i^4=1$ — so only the exponent's remainder mod 4 matters.", example: "$i^{27} = i^{27\\bmod4} = i^3 = -i$." },
    ],
  },
  {
    key: "trig",
    navLabel: "Trigonometry",
    title: "Trigonometry Definitions",
    description: "Core vocabulary for trigonometry, used in the Trigonometry calculator.",
    definitions: [
      { term: "Angle", definition: "A measure of rotation between two rays sharing an endpoint, measured in degrees or radians.", example: "A right angle measures $90°$, equivalent to $\\pi/2$ radians." },
      { term: "Radian", definition: "The angle subtended at the center of a circle by an arc equal in length to the circle's radius — the natural unit of angle in calculus.", example: "A full circle is $2\\pi$ radians, equal to $360°$." },
      { term: "Sine, Cosine, Tangent", definition: "The three basic trig ratios of a right triangle's angle: sine = opposite/hypotenuse, cosine = adjacent/hypotenuse, tangent = opposite/adjacent.", example: "In a 3-4-5 right triangle, $\\sin\\theta = 3/5$ for the angle opposite the side of length 3." },
      { term: "Reciprocal Functions", definition: "Secant, cosecant, and cotangent — the reciprocals of cosine, sine, and tangent respectively.", example: "$\\sec\\theta = \\frac{1}{\\cos\\theta}$." },
      { term: "Unit Circle", definition: "A circle of radius $1$ centered at the origin, used to define sine and cosine for any angle (not just triangle angles between $0°$ and $90°$).", example: "On the unit circle, the point at angle $90°$ is $(0,1)$, so $\\sin90°=1$ and $\\cos90°=0$." },
      { term: "Trigonometric Identity", definition: "An equation involving trig functions that's true for every value of the variable (not just specific solutions).", example: "$\\sin^2\\theta+\\cos^2\\theta=1$ holds for every angle $\\theta$." },
      { term: "Periodic Function", definition: "A function that repeats its values in a regular pattern over a fixed interval (its period).", example: "$\\sin\\theta$ has period $360°$ (or $2\\pi$): $\\sin(\\theta+360°)=\\sin\\theta$." },
      { term: "Reference Angle", definition: "The acute angle between the terminal side of an angle and the x-axis — used to find trig values for angles outside $0°$–$90°$.", example: "The reference angle for $150°$ is $30°$." },
      { term: "Amplitude", definition: "Half the distance between a wave's maximum and minimum — the coefficient $|a|$ in $y=a\\sin(bx+c)+d$.", example: "$y=3\\sin x$ has amplitude $3$, oscillating between $-3$ and $3$." },
      { term: "Period and Frequency", definition: "The period is the horizontal length of one complete cycle; for $y=a\\sin(bx)$ it is $\\frac{2\\pi}{|b|}$. Frequency is the number of cycles per unit — its reciprocal.", example: "$y=\\sin(2x)$ has period $\\pi$ — it cycles twice as fast as $\\sin x$." },
      { term: "Phase Shift", definition: "A horizontal slide of a trig graph — for $y=\\sin(bx+c)$ it equals $-\\frac{c}{b}$, positive meaning a shift right.", example: "$y=\\sin(x-\\frac{\\pi}{2})$ is $\\sin x$ shifted right by $\\frac{\\pi}{2}$ — which is exactly $-\\cos x$." },
      { term: "Quadrant Signs (ASTC)", definition: "Which functions are positive by quadrant: All in I, Sine in II, Tangent in III, Cosine in IV.", example: "At $210°$ (quadrant III), $\\tan$ is positive while $\\sin$ and $\\cos$ are negative." },
      { term: "Pythagorean Identities", definition: "The three identities that follow from $x^2+y^2=1$ on the unit circle: $\\sin^2\\theta+\\cos^2\\theta=1$, $1+\\tan^2\\theta=\\sec^2\\theta$, and $1+\\cot^2\\theta=\\csc^2\\theta$.", example: "If $\\sin\\theta=\\frac35$ in quadrant I, then $\\cos\\theta=\\sqrt{1-\\frac{9}{25}}=\\frac45$." },
      { term: "Cofunction Identity", definition: "Each function of an angle equals its co-function of the complementary angle: $\\sin(90°-\\theta)=\\cos\\theta$, and likewise for $\\tan/\\cot$ and $\\sec/\\csc$.", example: "$\\sin 70° = \\cos 20°$." },
      { term: "Sum and Difference Formulas", definition: "$\\sin(A\\pm B)=\\sin A\\cos B\\pm\\cos A\\sin B$ and $\\cos(A\\pm B)=\\cos A\\cos B\\mp\\sin A\\sin B$ — note the flipped sign in the cosine version.", example: "$\\cos75° = \\cos(45°+30°) = \\frac{\\sqrt6-\\sqrt2}{4}$." },
      { term: "Double Angle Formulas", definition: "$\\sin2\\theta=2\\sin\\theta\\cos\\theta$ and $\\cos2\\theta=\\cos^2\\theta-\\sin^2\\theta=1-2\\sin^2\\theta=2\\cos^2\\theta-1$.", example: "If $\\sin\\theta=\\frac35$ and $\\cos\\theta=\\frac45$, then $\\sin2\\theta=\\frac{24}{25}$." },
      { term: "Half Angle Formulas", definition: "$\\sin\\frac{\\theta}{2}=\\pm\\sqrt{\\frac{1-\\cos\\theta}{2}}$ and $\\cos\\frac{\\theta}{2}=\\pm\\sqrt{\\frac{1+\\cos\\theta}{2}}$, with the sign set by the half-angle's quadrant.", example: "$\\cos 22.5° = \\sqrt{\\frac{1+\\frac{\\sqrt2}{2}}{2}}\\approx0.924$." },
      { term: "Law of Sines", definition: "In any triangle, each side is proportional to the sine of its opposite angle: $\\frac{a}{\\sin A}=\\frac{b}{\\sin B}=\\frac{c}{\\sin C}$.", example: "Used when you know two angles and a side (AAS/ASA), or two sides and a non-included angle." },
      { term: "Law of Cosines", definition: "A generalization of the Pythagorean theorem to any triangle: $c^2=a^2+b^2-2ab\\cos C$ — it reduces to $a^2+b^2$ when $C=90°$.", example: "With $a=5$, $b=7$, $C=60°$: $c^2=25+49-35=39$, so $c\\approx6.24$." },
      { term: "Inverse Trig Function", definition: "The function that returns the angle for a given ratio, written $\\sin^{-1}$ or $\\arcsin$. To stay a function, its output is restricted to a principal range.", example: "$\\sin^{-1}(0.5)=30°$ — the calculator never returns $150°$, even though $\\sin150°=0.5$ too." },
      { term: "General Solution of a Trig Equation", definition: "Because trig functions repeat, every solution is one base angle plus whole multiples of the period: e.g. $\\sin\\theta=k$ gives $\\theta = \\theta_0+360°n$ and $\\theta = 180°-\\theta_0+360°n$.", example: "$\\sin\\theta=\\frac12$ gives $\\theta = 30°+360°n$ or $150°+360°n$." },
      { term: "Degree–Radian Conversion", definition: "Multiply by $\\frac{\\pi}{180}$ to go from degrees to radians, and by $\\frac{180}{\\pi}$ to come back.", example: "$135° = 135\\cdot\\frac{\\pi}{180} = \\frac{3\\pi}{4}$ radians." },
      { term: "Arc Length and Sector Area", definition: "With $\\theta$ in RADIANS, an arc has length $s=r\\theta$ and the sector it cuts has area $A=\\frac12r^2\\theta$.", example: "A $60°$ sector of radius 6: $\\theta=\\frac{\\pi}{3}$, $s=2\\pi$, $A=6\\pi$." },
    ],
  },
  {
    key: "shapes",
    navLabel: "Shapes",
    title: "Geometry Definitions",
    description: "Core vocabulary for 2D shapes and 3D solids, each with a labeled diagram — used throughout the Shapes calculator.",
    definitions: [
      { term: "Angle", definition: "The amount of turn between two rays that meet at a shared endpoint (the vertex), measured in degrees or radians.", example: "A right angle is $90°$; a straight angle is $180°$.", diagram: "angle" },
      { term: "Vertex", definition: "A corner point where two sides (or edges) of a shape meet.", example: "A triangle has 3 vertices; a cube has 8." },
      { term: "Perimeter", definition: "The total distance around the outside of a two-dimensional shape — add up every side.", example: "A rectangle with sides 4 and 6 has perimeter $2(4+6)=20$.", diagram: "rectangle" },
      { term: "Area", definition: "The amount of two-dimensional space enclosed within a shape's boundary, measured in square units.", example: "A rectangle with $l=6$ and $w=4$ has area $A = l\\times w = 24$.", diagram: "rectangle" },
      { term: "Polygon", definition: "A closed two-dimensional shape made only of straight line segments — no curves, no gaps.", example: "Triangles, rectangles, and pentagons are polygons; circles are not.", diagram: "polygon" },
      { term: "Regular Polygon", definition: "A polygon where every side has the same length AND every interior angle is equal. The distance from the center to a side is the apothem $a$; to a vertex is the circumradius $R$.", example: "A regular pentagon's area is $A = \\tfrac{1}{2}\\,a\\,P$, where $P$ is its perimeter.", diagram: "regular-polygon" },
      { term: "Triangle", definition: "A three-sided polygon. Its area uses any side as the base $b$ together with the perpendicular height $h$ drawn to it.", example: "$A = \\tfrac{1}{2}bh$; with $b=12$ and $h=8$, $A=48$.", diagram: "triangle" },
      { term: "Right Triangle", definition: "A triangle containing one $90°$ angle. The side opposite the right angle is the hypotenuse — always the longest side.", example: "Sides $3$ and $4$ give hypotenuse $5$, since $3^2+4^2=5^2$.", diagram: "right-triangle" },
      { term: "Pythagorean Theorem", definition: "In any right triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: $a^2+b^2=c^2$.", example: "With legs $6$ and $8$: $c=\\sqrt{36+64}=10$.", diagram: "right-triangle" },
      { term: "Heron's Formula", definition: "A way to find a triangle's area from its three sides alone (no height needed), using the semi-perimeter $s=\\frac{a+b+c}{2}$: $A=\\sqrt{s(s-a)(s-b)(s-c)}$.", example: "For sides $3,4,5$: $s=6$ and $A=\\sqrt{6\\cdot3\\cdot2\\cdot1}=6$." },
      { term: "Triangle Inequality", definition: "Three lengths can form a triangle only if each pair of sides adds up to more than the third side.", example: "$2, 3, 9$ cannot form a triangle, since $2+3 < 9$." },
      { term: "Quadrilateral", definition: "Any four-sided polygon. Its interior angles always add to $360°$.", example: "Squares, rectangles, rhombuses, and trapezoids are all quadrilaterals." },
      { term: "Parallelogram", definition: "A quadrilateral with both pairs of opposite sides parallel (and therefore equal). Its area uses the perpendicular height, not the slanted side.", example: "$A = b\\times h$; with $b=6$, $h=4$, $A=24$.", diagram: "parallelogram" },
      { term: "Trapezoid", definition: "A quadrilateral with exactly one pair of parallel sides ($a$ and $b$), separated by the perpendicular height $h$.", example: "$A=\\tfrac{1}{2}(a+b)h$; with $a=4$, $b=8$, $h=5$: $A=30$.", diagram: "trapezoid" },
      { term: "Rhombus", definition: "A parallelogram with all four sides equal. Its diagonals $d_1$ and $d_2$ cross at right angles and bisect each other.", example: "$A=\\tfrac{1}{2}d_1d_2$; with $d_1=6$, $d_2=8$: $A=24$.", diagram: "rhombus" },
      { term: "Radius", definition: "The distance from a circle's center to any point on the circle — every radius of a given circle is the same length.", example: "A circle with diameter 10 has radius 5.", diagram: "circle-radius" },
      { term: "Diameter", definition: "The distance straight across a circle through its center — exactly twice the radius, and the longest chord possible.", example: "A circle with radius 5 has diameter 10.", diagram: "circle-diameter" },
      { term: "Chord", definition: "A line segment joining two points on a circle. It need not pass through the center (a diameter is the special case that does).", example: "Any straight line drawn between two points on a circle's edge is a chord.", diagram: "chord" },
      { term: "Arc", definition: "A connected portion of a circle's circumference between two points on the circle. Its length is $s=r\\theta$ with $\\theta$ in radians.", example: "A quarter-circle arc of radius 4 has length $4\\cdot\\frac{\\pi}{2}\\approx6.28$.", diagram: "arc" },
      { term: "Sector", definition: "A \"pie-slice\" region bounded by two radii and the arc between them, with central angle $\\theta$.", example: "$A=\\tfrac{1}{2}r^2\\theta$ (radians); a $90°$ sector of radius 4 has area $4\\pi\\approx12.57$.", diagram: "sector" },
      { term: "Circumference", definition: "The perimeter of a circle — the distance all the way around it: $C=2\\pi r=\\pi d$.", example: "A circle of radius 5 has $C=10\\pi\\approx31.42$.", diagram: "circle-radius" },
      { term: "Ring (Annulus)", definition: "The region between two concentric circles of outer radius $R$ and inner radius $r$ — a washer shape.", example: "$A=\\pi(R^2-r^2)$; with $R=8$, $r=5$: $A=39\\pi\\approx122.5$.", diagram: "ring" },
      { term: "Ellipse", definition: "A stretched circle, described by a semi-major axis $a$ (the longer half-width) and a semi-minor axis $b$.", example: "$A=\\pi ab$; with $a=5$, $b=3$: $A=15\\pi\\approx47.12$.", diagram: "ellipse" },
      { term: "Apothem", definition: "In a regular polygon, the perpendicular distance from the center to the midpoint of any side.", example: "A regular hexagon of side $s$ has apothem $a=\\frac{s\\sqrt3}{2}$.", diagram: "regular-polygon" },
      { term: "Congruent", definition: "Two shapes are congruent if they have exactly the same size AND shape — one can be slid, turned, or flipped onto the other perfectly.", example: "Two circles with the same radius are always congruent.", diagram: "congruent" },
      { term: "Similar", definition: "Two shapes are similar if they have the same shape but possibly different sizes: corresponding angles are equal and corresponding sides are all in the same ratio.", example: "Any two squares are similar, whatever their side lengths.", diagram: "similar" },
      { term: "Surface Area", definition: "The total area of all the outer faces (or curved surface) of a 3D solid — the amount of wrapping paper it would take.", example: "A cube of side $s$ has surface area $6s^2$.", diagram: "cube" },
      { term: "Volume", definition: "The amount of three-dimensional space a solid occupies, measured in cubic units.", example: "A cuboid with $l=5$, $w=3$, $h=2$ has volume $30$ cubic units.", diagram: "cuboid" },
      { term: "Cube", definition: "A solid with six identical square faces, all edges of equal length $s$.", example: "$V=s^3$ and surface area $=6s^2$; for $s=4$: $V=64$, $SA=96$.", diagram: "cube" },
      { term: "Cuboid (Rectangular Prism)", definition: "A box-shaped solid with six rectangular faces, described by length, width, and height.", example: "$V=l\\,w\\,h$ and $SA=2(lw+wh+hl)$.", diagram: "cuboid" },
      { term: "Cylinder", definition: "A solid with two parallel circular ends of radius $r$ joined by a curved surface of height $h$.", example: "$V=\\pi r^2h$; curved surface $=2\\pi rh$; total $SA=2\\pi r(r+h)$.", diagram: "cylinder" },
      { term: "Cone", definition: "A solid with a circular base of radius $r$ narrowing to a single apex, with vertical height $h$ and slant height $l=\\sqrt{r^2+h^2}$.", example: "$V=\\tfrac{1}{3}\\pi r^2h$; curved surface $=\\pi r l$.", diagram: "cone" },
      { term: "Sphere", definition: "The set of all points a fixed distance $r$ from a center point — a perfectly round solid.", example: "$V=\\tfrac{4}{3}\\pi r^3$ and $SA=4\\pi r^2$; for $r=3$: $V=36\\pi$, $SA=36\\pi$.", diagram: "sphere" },
      { term: "Slant Height", definition: "For a cone or pyramid, the distance measured along the sloping surface from the apex to the edge of the base — longer than the vertical height.", example: "A cone with $r=3$, $h=4$ has slant height $l=\\sqrt{9+16}=5$.", diagram: "cone" },
    ],
  },
  {
    key: "numtheory",
    navLabel: "Number Theory",
    title: "Number Theory Definitions",
    description: "Core vocabulary for number theory, used in the Number Theory calculator.",
    definitions: [
      { term: "Prime Number", definition: "A whole number greater than 1 with exactly two divisors: 1 and itself.", example: "$7$ is prime — only $1$ and $7$ divide it evenly." },
      { term: "Composite Number", definition: "A whole number greater than 1 with more than two divisors (i.e., not prime).", example: "$12$ is composite — divisible by $1,2,3,4,6,12$." },
      { term: "Factor (Divisor)", definition: "A whole number that divides another number exactly, with no remainder.", example: "The factors of $12$ are $1,2,3,4,6,12$." },
      { term: "Multiple", definition: "The product of a number and any whole number — what you get by \"multiplying it up\".", example: "The first few multiples of $4$ are $4, 8, 12, 16, \\dots$" },
      { term: "Greatest Common Divisor (GCD)", definition: "The largest whole number that divides two (or more) numbers exactly.", example: "$\\gcd(12, 18) = 6$." },
      { term: "Least Common Multiple (LCM)", definition: "The smallest whole number that is a multiple of two (or more) numbers.", example: "$\\text{lcm}(4, 6) = 12$." },
      { term: "Coprime Numbers", definition: "Two numbers whose greatest common divisor is $1$ — they share no common factors other than 1.", example: "$8$ and $9$ are coprime, even though neither is prime." },
      { term: "Prime Factorization", definition: "Writing a number as a product of prime numbers.", example: "$60 = 2^2\\times 3\\times 5$." },
      { term: "Divisibility Rules", definition: "Quick digit tests for factors: a number is divisible by 3 if its digit sum is, by 4 if its last two digits are, by 9 if its digit sum is, and by 11 if the alternating digit sum is.", example: "$1{,}236$: digits sum to 12, divisible by 3, so $1{,}236$ is too." },
      { term: "Euclidean Algorithm", definition: "A fast GCD method: repeatedly replace the larger number with the remainder of dividing it by the smaller, until the remainder is 0 — the last non-zero value is the GCD.", example: "$\\gcd(48,18)$: $48=2(18)+12$, $18=1(12)+6$, $12=2(6)+0$, so the GCD is $6$." },
      { term: "Fundamental Theorem of Arithmetic", definition: "Every whole number above 1 factors into primes in exactly one way, apart from the order of the factors.", example: "$360 = 2^3\\times3^2\\times5$ — no other prime factorization exists." },
      { term: "Modular Arithmetic (Congruence)", definition: "$a\\equiv b \\pmod m$ means $a$ and $b$ leave the same remainder when divided by $m$ — clock arithmetic.", example: "$17\\equiv5\\pmod{12}$, which is why 17:00 reads as 5 o'clock." },
      { term: "GCD × LCM Identity", definition: "For any two positive integers, $\\gcd(a,b)\\times\\text{lcm}(a,b) = a\\times b$ — so knowing one gives the other instantly.", example: "$\\gcd(12,18)=6$, so $\\text{lcm}(12,18) = \\frac{12\\times18}{6}=36$." },
      { term: "Sieve of Eratosthenes", definition: "An ancient method for listing primes: write the numbers up to $n$, then repeatedly cross out every multiple of the next surviving number.", example: "Sieving to 30 leaves $2,3,5,7,11,13,17,19,23,29$." },
      { term: "Euler's Totient Function φ(n)", definition: "The count of numbers from 1 to $n$ that are coprime to $n$. For a prime $p$, $\\varphi(p)=p-1$.", example: "$\\varphi(12)=4$, counting $1,5,7,11$." },
      { term: "Fermat's Little Theorem", definition: "If $p$ is prime and $a$ isn't a multiple of $p$, then $a^{p-1}\\equiv1\\pmod p$ — the backbone of many primality tests.", example: "$2^{6} = 64 \\equiv 1 \\pmod 7$." },
      { term: "Perfect Number", definition: "A number equal to the sum of its proper divisors (all divisors except itself).", example: "$28 = 1+2+4+7+14$." },
      { term: "Twin Primes", definition: "A pair of primes differing by exactly 2.", example: "$(11,13)$ and $(17,19)$ are twin prime pairs." },
      { term: "Quotient and Remainder (Division Algorithm)", definition: "For integers $a$ and $b>0$ there are unique $q$ and $r$ with $a=bq+r$ and $0\\le r<b$.", example: "$47 = 5(9)+2$, so dividing 47 by 5 gives quotient 9, remainder 2." },
    ],
  },
  {
    key: "numsystems",
    navLabel: "Number Systems",
    title: "Number System Definitions",
    description: "Core vocabulary for number systems and bases, used in the Number Systems calculator.",
    definitions: [
      { term: "Number System (Base/Radix)", definition: "A system for writing numbers using a fixed set of digits, where each digit's position represents a power of the \"base\".", example: "Decimal (base 10) uses digits 0-9; binary (base 2) uses only 0 and 1." },
      { term: "Binary (Base 2)", definition: "A number system using only the digits 0 and 1 — the native language of computer hardware.", example: "$1011_2 = 8+0+2+1 = 11_{10}$." },
      { term: "Octal (Base 8)", definition: "A number system using digits 0-7.", example: "$17_8 = 1\\times8+7 = 15_{10}$." },
      { term: "Decimal (Base 10)", definition: "The everyday number system using digits 0-9 — based on 10 fingers.", example: "$253_{10} = 2\\times100+5\\times10+3$." },
      { term: "Hexadecimal (Base 16)", definition: "A number system using digits 0-9 plus letters A-F (for 10-15) — commonly used to represent computer memory addresses and colors compactly.", example: "$2F_{16} = 2\\times16+15 = 47_{10}$." },
      { term: "Place Value", definition: "The value a digit represents based on its position in a number, determined by powers of the base.", example: "In $253_{10}$, the '5' is in the tens place, worth $5\\times10^1=50$." },
      { term: "Bit", definition: "A single binary digit (0 or 1) — the smallest unit of digital information.", example: "The binary number $1011$ has 4 bits." },
      { term: "Bit, Nibble, Byte", definition: "A bit is one binary digit; 4 bits make a nibble (exactly one hex digit); 8 bits make a byte (two hex digits), holding values $0$–$255$.", example: "$1111\\,1111_2 = FF_{16} = 255_{10}$ — one full byte." },
      { term: "Base Conversion by Repeated Division", definition: "To convert a decimal number to base $b$, divide repeatedly by $b$ and collect the remainders — then read them bottom to top.", example: "$13\\div2$ gives remainders $1,0,1,1$ upward, so $13_{10}=1101_2$." },
      { term: "Expansion Method (to Decimal)", definition: "To convert to decimal, multiply each digit by its place value (a power of the base) and add the results.", example: "$2A_{16} = 2(16)+10 = 42_{10}$." },
      { term: "Binary Addition", definition: "Adding bit by bit with carries: $0+0=0$, $0+1=1$, and $1+1=10$ (write 0, carry 1).", example: "$1011_2+0110_2 = 10001_2$ (that is $11+6=17$)." },
      { term: "Two's Complement", definition: "The standard way computers store negative integers: invert every bit of the positive value, then add 1. The leading bit becomes the sign.", example: "In 8 bits, $-5$ is $1111\\,1011_2$." },
      { term: "Signed vs Unsigned", definition: "Unsigned bits all carry magnitude; signed formats spend the leading bit on the sign, halving the positive range.", example: "8 bits hold $0$–$255$ unsigned, but $-128$–$127$ signed." },
      { term: "Binary ↔ Hexadecimal Shortcut", definition: "Hex digits map exactly to 4-bit groups, so conversion needs no arithmetic — just group the bits in fours from the right.", example: "$1101\\,0110_2 \\to D6_{16}$." },
      { term: "Binary ↔ Octal Shortcut", definition: "The same trick with groups of three bits, since $8=2^3$.", example: "$110\\,101_2 \\to 65_8$." },
      { term: "Fractional (Binary Point) Values", definition: "Digits after the point carry negative powers of the base: $\\frac12$, $\\frac14$, $\\frac18$, and so on.", example: "$0.101_2 = \\frac12+\\frac18 = 0.625_{10}$." },
      { term: "Overflow", definition: "What happens when a result needs more bits than the format has — the extra high bits are lost and the value wraps around.", example: "In 8 unsigned bits, $255+1$ wraps to $0$." },
      { term: "ASCII", definition: "A 7-bit code assigning a number to each basic text character, so text can be stored as binary.", example: "'A' is $65_{10} = 0100\\,0001_2$; 'a' is $97_{10}$." },
    ],
  },
];
