import type { DefinitionTopic } from "./definitions-data";
import { latexToPlainText, sanitizeAsciiForPdf } from "./latex-to-text";

// Same fixed, hardcoded palette as pdf-export.ts (formula sheets) — kept
// consistent across both PDF exports rather than reading the app's live
// oklch-based theme variables.
const COLORS = {
  headerFrom: [79, 70, 229] as [number, number, number],
  headerTo: [124, 58, 237] as [number, number, number],
  headerText: [255, 255, 255] as [number, number, number],
  headerSubtext: [224, 217, 251] as [number, number, number],
  text: [30, 27, 46] as [number, number, number],
  muted: [107, 101, 128] as [number, number, number],
  cardBg: [248, 247, 252] as [number, number, number],
  cardBorder: [230, 226, 242] as [number, number, number],
  accentBar: [124, 58, 237] as [number, number, number],
  footerText: [163, 156, 192] as [number, number, number],
};

function formatGeneratedDate(): string {
  return new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
}

/** Converts a definition/example string that may contain inline `$...$`
 *  math segments into fully plain text, for jsPDF's text API — and
 *  sanitizes the surrounding prose too (not just the math parts), since
 *  plain English text can just as easily contain a stray em-dash, curly
 *  quote, or degree sign that jsPDF's built-in fonts can't render. */
function plainize(text: string): string {
  const withMathConverted = text.replace(/\$([^$]+)\$/g, (_m, inner: string) => latexToPlainText(inner));
  return sanitizeAsciiForPdf(withMathConverted);
}

/**
 * Draws a definitions topic straight to jsPDF using its native text/shape
 * API — the same reliable, no-DOM-screenshot approach as pdf-export.ts
 * (formula sheets), single-column since definitions run longer than
 * formulas and read better at full width.
 */
export async function exportDefinitionsPDF(topic: DefinitionTopic): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF("p", "pt", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  const footerHeight = 34;
  const contentBottom = pageHeight - footerHeight - 16;

  let page = 1;

  const drawFooter = () => {
    pdf.setDrawColor(...COLORS.cardBorder);
    pdf.line(margin, pageHeight - footerHeight, pageWidth - margin, pageHeight - footerHeight);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...COLORS.footerText);
    pdf.text("Generated by Calculin - calculin.vercel.app", margin, pageHeight - footerHeight + 16);
    pdf.text(`${formatGeneratedDate()} - Page ${page}`, pageWidth - margin, pageHeight - footerHeight + 16, { align: "right" });
  };

  const drawHeaderBand = (compact: boolean): number => {
    const bandHeight = compact ? 56 : 128;
    const steps = 24;
    for (let i = 0; i < steps; i++) {
      const t = i / (steps - 1);
      const r = Math.round(COLORS.headerFrom[0] + (COLORS.headerTo[0] - COLORS.headerFrom[0]) * t);
      const g = Math.round(COLORS.headerFrom[1] + (COLORS.headerTo[1] - COLORS.headerFrom[1]) * t);
      const b = Math.round(COLORS.headerFrom[2] + (COLORS.headerTo[2] - COLORS.headerFrom[2]) * t);
      pdf.setFillColor(r, g, b);
      const stripW = pageWidth / steps;
      pdf.rect(i * stripW, 0, stripW + 1, bandHeight, "F");
    }

    pdf.setFillColor(255, 255, 255);
    pdf.roundedRect(margin, compact ? 14 : 28, 26, 26, 6, 6, "F");
    pdf.setTextColor(...COLORS.headerFrom);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("C", margin + 13, compact ? 32 : 46, { align: "center" });

    pdf.setTextColor(...COLORS.headerText);
    pdf.setFontSize(13);
    pdf.text("Calculin", margin + 34, compact ? 31 : 45);

    if (!compact) {
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(24);
      pdf.text(sanitizeAsciiForPdf(topic.title), margin, 82);

      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);
      pdf.setTextColor(...COLORS.headerSubtext);
      const descLines = pdf.splitTextToSize(sanitizeAsciiForPdf(topic.description), pageWidth - margin * 2);
      pdf.text(descLines, margin, 104);
    } else {
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(12);
      pdf.text(sanitizeAsciiForPdf(topic.title), pageWidth - margin, 34, { align: "right" });
    }

    return bandHeight;
  };

  const startNewPage = () => {
    pdf.addPage();
    page++;
    const bandHeight = drawHeaderBand(true);
    drawFooter();
    return bandHeight + 20;
  };

  let y = drawHeaderBand(false) + 30;
  drawFooter();

  topic.definitions.forEach((d) => {
    const defText = plainize(d.definition);
    const exText = d.example ? plainize(d.example) : "";

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    const defLines: string[] = pdf.splitTextToSize(defText, contentWidth - 24);

    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(9);
    const exLines: string[] = exText ? pdf.splitTextToSize(`Example: ${exText}`, contentWidth - 24) : [];

    const termHeight = 17;
    const defHeight = defLines.length * 13;
    const exHeight = exLines.length ? exLines.length * 12 + 8 : 0;
    const cardHeight = termHeight + defHeight + exHeight + 16;

    if (y + cardHeight > contentBottom) {
      y = startNewPage();
    }

    pdf.setFillColor(...COLORS.cardBg);
    pdf.setDrawColor(...COLORS.cardBorder);
    pdf.roundedRect(margin, y, contentWidth, cardHeight, 4, 4, "FD");
    pdf.setFillColor(...COLORS.accentBar);
    pdf.rect(margin, y, 3, cardHeight, "F");

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(11);
    pdf.setTextColor(...COLORS.text);
    pdf.text(sanitizeAsciiForPdf(d.term), margin + 14, y + 17);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(10);
    pdf.setTextColor(...COLORS.text);
    pdf.text(defLines, margin + 14, y + 17 + 15);

    if (exLines.length) {
      pdf.setFont("helvetica", "italic");
      pdf.setFontSize(9);
      pdf.setTextColor(...COLORS.muted);
      pdf.text(exLines, margin + 14, y + 17 + defHeight + 18);
    }

    y += cardHeight + 10;
  });

  pdf.save(`Calculin-${topic.key}-definitions.pdf`);
}
