export interface FormulaEntry {
  name: string;
  /** LaTeX, rendered via KaTeX */
  latex: string;
  /** Optional short clarifying note (plain text, may include $inline$ math) */
  note?: string;
}

export interface FormulaTopic {
  key: string;
  /** Shown in the header sub-row / mobile menu */
  navLabel: string;
  /** Shown as the on-page and PDF heading, e.g. "Derivative Formulas" */
  title: string;
  /** One-line description shown under the heading and in the PDF */
  description: string;
  formulas: FormulaEntry[];
}

export const FORMULA_TOPICS: FormulaTopic[] = [
  {
    key: "derivative",
    navLabel: "Derivatives",
    title: "Derivative Formulas",
    description: "Standard differentiation rules — the ones used throughout the Derivative calculator.",
    formulas: [
      { name: "Constant Rule", latex: "\\frac{d}{dx}[c] = 0" },
      { name: "Power Rule", latex: "\\frac{d}{dx}[x^n] = nx^{n-1}" },
      { name: "Constant Multiple Rule", latex: "\\frac{d}{dx}[c\\cdot f(x)] = c\\cdot f'(x)" },
      { name: "Sum Rule", latex: "\\frac{d}{dx}[f(x) + g(x)] = f'(x) + g'(x)" },
      { name: "Difference Rule", latex: "\\frac{d}{dx}[f(x) - g(x)] = f'(x) - g'(x)" },
      { name: "Product Rule", latex: "\\frac{d}{dx}[f(x)g(x)] = f'(x)g(x) + f(x)g'(x)" },
      { name: "Quotient Rule", latex: "\\frac{d}{dx}\\left[\\frac{f(x)}{g(x)}\\right] = \\frac{f'(x)g(x) - f(x)g'(x)}{g(x)^2}" },
      { name: "Chain Rule", latex: "\\frac{d}{dx}[f(g(x))] = f'(g(x))\\cdot g'(x)" },
      { name: "Bare Variable", latex: "\\frac{d}{dx}[x] = 1" },
      { name: "Derivative of √x", latex: "\\frac{d}{dx}[\\sqrt{x}] = \\frac{1}{2\\sqrt{x}}" },
      { name: "Derivative of 1/x", latex: "\\frac{d}{dx}\\left[\\frac{1}{x}\\right] = -\\frac{1}{x^2}" },
      { name: "Derivative of eˣ", latex: "\\frac{d}{dx}[e^x] = e^x" },
      { name: "Derivative of aˣ", latex: "\\frac{d}{dx}[a^x] = a^x \\ln a" },
      { name: "Derivative of ln x", latex: "\\frac{d}{dx}[\\ln x] = \\frac{1}{x}" },
      { name: "Derivative of logₐ x", latex: "\\frac{d}{dx}[\\log_a x] = \\frac{1}{x\\ln a}" },
      { name: "Derivative of sin", latex: "\\frac{d}{dx}[\\sin x] = \\cos x" },
      { name: "Derivative of cos", latex: "\\frac{d}{dx}[\\cos x] = -\\sin x" },
      { name: "Derivative of tan", latex: "\\frac{d}{dx}[\\tan x] = \\sec^2 x" },
      { name: "Derivative of cot", latex: "\\frac{d}{dx}[\\cot x] = -\\csc^2 x" },
      { name: "Derivative of sec", latex: "\\frac{d}{dx}[\\sec x] = \\sec x\\tan x" },
      { name: "Derivative of csc", latex: "\\frac{d}{dx}[\\csc x] = -\\csc x\\cot x" },
      { name: "Derivative of arcsin", latex: "\\frac{d}{dx}[\\arcsin x] = \\frac{1}{\\sqrt{1-x^2}}" },
      { name: "Derivative of arccos", latex: "\\frac{d}{dx}[\\arccos x] = -\\frac{1}{\\sqrt{1-x^2}}" },
      { name: "Derivative of arctan", latex: "\\frac{d}{dx}[\\arctan x] = \\frac{1}{1+x^2}" },
    ],
  },
  {
    key: "integration",
    navLabel: "Integrals",
    title: "Integration Formulas",
    description: "Standard antiderivatives — the ones used throughout the Integration calculator.",
    formulas: [
      { name: "Power Rule", latex: "\\int x^n\\,dx = \\frac{x^{n+1}}{n+1} + C", note: "for $n \\neq -1$" },
      { name: "Reciprocal Rule", latex: "\\int \\frac{1}{x}\\,dx = \\ln|x| + C" },
      { name: "Constant Rule", latex: "\\int k\\,dx = kx + C" },
      { name: "Constant Multiple Rule", latex: "\\int c\\cdot f(x)\\,dx = c\\int f(x)\\,dx" },
      { name: "Sum Rule", latex: "\\int [f(x) + g(x)]\\,dx = \\int f(x)\\,dx + \\int g(x)\\,dx" },
      { name: "Difference Rule", latex: "\\int [f(x) - g(x)]\\,dx = \\int f(x)\\,dx - \\int g(x)\\,dx" },
      { name: "Integral of √x", latex: "\\int \\sqrt{x}\\,dx = \\frac{2}{3}x^{3/2} + C" },
      { name: "Integral of sin", latex: "\\int \\sin x\\,dx = -\\cos x + C" },
      { name: "Integral of cos", latex: "\\int \\cos x\\,dx = \\sin x + C" },
      { name: "Integral of sec²", latex: "\\int \\sec^2 x\\,dx = \\tan x + C" },
      { name: "Integral of csc²", latex: "\\int \\csc^2 x\\,dx = -\\cot x + C" },
      { name: "Integral of sec·tan", latex: "\\int \\sec x\\tan x\\,dx = \\sec x + C" },
      { name: "Integral of csc·cot", latex: "\\int \\csc x\\cot x\\,dx = -\\csc x + C" },
      { name: "Integral of tan", latex: "\\int \\tan x\\,dx = -\\ln|\\cos x| + C" },
      { name: "Integral of cot", latex: "\\int \\cot x\\,dx = \\ln|\\sin x| + C" },
      { name: "Integral of sec", latex: "\\int \\sec x\\,dx = \\ln|\\sec x + \\tan x| + C" },
      { name: "Integral of eˣ", latex: "\\int e^x\\,dx = e^x + C" },
      { name: "Integral of aˣ", latex: "\\int a^x\\,dx = \\frac{a^x}{\\ln a} + C" },
      { name: "Integral of ln x", latex: "\\int \\ln x\\,dx = x\\ln x - x + C" },
      { name: "Integral — 1/(1+x²)", latex: "\\int \\frac{1}{1+x^2}\\,dx = \\arctan x + C" },
      { name: "Integral — 1/√(1-x²)", latex: "\\int \\frac{1}{\\sqrt{1-x^2}}\\,dx = \\arcsin x + C" },
      { name: "Fundamental Theorem of Calculus", latex: "\\int_a^b f(x)\\,dx = F(b) - F(a)" },
      { name: "Area Between Two Bounds", latex: "\\int_a^b f(x)\\,dx = -\\int_b^a f(x)\\,dx" },
    ],
  },
  {
    key: "limits",
    navLabel: "Limits",
    title: "Limit Formulas",
    description: "Core limit laws and standard limit results used in the Limits calculator.",
    formulas: [
      { name: "Sum Law", latex: "\\lim_{x\\to a}[f(x)+g(x)] = \\lim_{x\\to a}f(x) + \\lim_{x\\to a}g(x)" },
      { name: "Difference Law", latex: "\\lim_{x\\to a}[f(x)-g(x)] = \\lim_{x\\to a}f(x) - \\lim_{x\\to a}g(x)" },
      { name: "Product Law", latex: "\\lim_{x\\to a}[f(x)g(x)] = \\lim_{x\\to a}f(x)\\cdot \\lim_{x\\to a}g(x)" },
      { name: "Quotient Law", latex: "\\lim_{x\\to a}\\frac{f(x)}{g(x)} = \\frac{\\lim_{x\\to a}f(x)}{\\lim_{x\\to a}g(x)}", note: "when the denominator's limit isn't $0$" },
      { name: "Constant Multiple Law", latex: "\\lim_{x\\to a} c\\cdot f(x) = c\\cdot\\lim_{x\\to a}f(x)" },
      { name: "Power Law", latex: "\\lim_{x\\to a} [f(x)]^n = \\left[\\lim_{x\\to a}f(x)\\right]^n" },
      { name: "Root Law", latex: "\\lim_{x\\to a} \\sqrt[n]{f(x)} = \\sqrt[n]{\\lim_{x\\to a}f(x)}" },
      { name: "Limit of a Constant", latex: "\\lim_{x\\to a} c = c" },
      { name: "Limit of x", latex: "\\lim_{x\\to a} x = a" },
      { name: "Limit of a Polynomial", latex: "\\lim_{x\\to a} p(x) = p(a)" },
      { name: "Famous Trig Limit", latex: "\\lim_{x\\to 0} \\frac{\\sin x}{x} = 1" },
      { name: "Related Trig Limit", latex: "\\lim_{x\\to 0} \\frac{1-\\cos x}{x} = 0" },
      { name: "Definition of e", latex: "\\lim_{x\\to \\infty} \\left(1+\\frac{1}{x}\\right)^x = e" },
      { name: "Definition of e (alt. form)", latex: "\\lim_{h\\to 0} \\left(1+h\\right)^{1/h} = e" },
      { name: "One-Sided Limits Agree ⇒ Limit Exists", latex: "\\lim_{x\\to a^-} f(x) = \\lim_{x\\to a^+} f(x) = L \\iff \\lim_{x\\to a} f(x) = L" },
      { name: "Continuity Check", latex: "f \\text{ is continuous at } a \\iff \\lim_{x\\to a}f(x) = f(a)" },
      { name: "Definition of a Derivative (as a Limit)", latex: "f'(x) = \\lim_{h\\to 0} \\frac{f(x+h)-f(x)}{h}" },
    ],
  },
  {
    key: "equations",
    navLabel: "Equations",
    title: "Equation-Solving Formulas",
    description: "Linear and quadratic equation formulas used in the Equation Solver.",
    formulas: [
      { name: "Linear Equation", latex: "ax + b = c \\;\\Rightarrow\\; x = \\frac{c-b}{a}", note: "for $a \\neq 0$" },
      { name: "Quadratic Formula", latex: "x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}" },
      { name: "Discriminant", latex: "D = b^2 - 4ac" },
      { name: "Discriminant — Two Real Roots", latex: "D > 0" },
      { name: "Discriminant — One Repeated Root", latex: "D = 0" },
      { name: "Discriminant — Complex Roots", latex: "D < 0" },
      { name: "Sum of Roots", latex: "x_1 + x_2 = -\\frac{b}{a}" },
      { name: "Product of Roots", latex: "x_1 \\cdot x_2 = \\frac{c}{a}" },
      { name: "Vertex of a Parabola", latex: "x = -\\frac{b}{2a}" },
      { name: "Standard Quadratic Form", latex: "ax^2+bx+c=0" },
      { name: "Difference of Squares", latex: "a^2-b^2 = (a-b)(a+b)" },
      { name: "Perfect Square Trinomial", latex: "a^2+2ab+b^2 = (a+b)^2" },
    ],
  },
  {
    key: "matrix",
    navLabel: "Matrices",
    title: "Matrix Formulas",
    description: "Determinant, inverse, and operation formulas used in the Matrix calculator.",
    formulas: [
      { name: "2×2 Determinant", latex: "\\det\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix} = ad-bc" },
      { name: "2×2 Inverse", latex: "\\begin{bmatrix}a&b\\\\c&d\\end{bmatrix}^{-1} = \\frac{1}{ad-bc}\\begin{bmatrix}d&-b\\\\-c&a\\end{bmatrix}", note: "when $\\det(A) \\neq 0$" },
      { name: "3×3 Determinant (Cofactor Expansion)", latex: "\\det(A) = a(ei-fh) - b(di-fg) + c(dh-eg)", note: "for $A=\\begin{bmatrix}a&b&c\\\\d&e&f\\\\g&h&i\\end{bmatrix}$" },
      { name: "Matrix Addition", latex: "(A+B)_{ij} = A_{ij} + B_{ij}" },
      { name: "Matrix Subtraction", latex: "(A-B)_{ij} = A_{ij} - B_{ij}" },
      { name: "Scalar Multiplication", latex: "(kA)_{ij} = k\\cdot A_{ij}" },
      { name: "Matrix Multiplication", latex: "(AB)_{ij} = \\sum_k A_{ik}B_{kj}" },
      { name: "Transpose", latex: "(A^T)_{ij} = A_{ji}" },
      { name: "Cramer's Rule", latex: "x_i = \\frac{\\det(A_i)}{\\det(A)}" },
      { name: "Identity Property", latex: "AI = IA = A" },
      { name: "Inverse Property", latex: "AA^{-1} = A^{-1}A = I" },
      { name: "Determinant of a Product", latex: "\\det(AB) = \\det(A)\\cdot\\det(B)" },
      { name: "Rank via Row Echelon Form", latex: "\\text{rank}(A) = \\text{number of non-zero rows in REF}" },
    ],
  },
  {
    key: "complex",
    navLabel: "Complex Numbers",
    title: "Complex Number Formulas",
    description: "Arithmetic, modulus, and polar-form formulas used in the Complex Number calculator.",
    formulas: [
      { name: "Imaginary Unit", latex: "i^2 = -1" },
      { name: "Powers of i (cycle)", latex: "i^1=i,\\ i^2=-1,\\ i^3=-i,\\ i^4=1" },
      { name: "Addition", latex: "(a+bi) + (c+di) = (a+c) + (b+d)i" },
      { name: "Subtraction", latex: "(a+bi) - (c+di) = (a-c) + (b-d)i" },
      { name: "Multiplication", latex: "(a+bi)(c+di) = (ac-bd) + (ad+bc)i" },
      { name: "Conjugate", latex: "\\overline{a+bi} = a-bi" },
      { name: "Modulus", latex: "|a+bi| = \\sqrt{a^2+b^2}" },
      { name: "Division", latex: "\\frac{z_1}{z_2} = \\frac{z_1 \\overline{z_2}}{|z_2|^2}" },
      { name: "Product with Conjugate", latex: "z\\overline{z} = |z|^2" },
      { name: "Polar Form", latex: "z = r(\\cos\\theta + i\\sin\\theta)" },
      { name: "Euler's Formula", latex: "e^{i\\theta} = \\cos\\theta + i\\sin\\theta" },
      { name: "Modulus in Polar Form", latex: "r = \\sqrt{a^2+b^2}" },
      { name: "Argument", latex: "\\theta = \\operatorname{atan2}(b, a)" },
      { name: "De Moivre's Theorem", latex: "z^n = r^n(\\cos n\\theta + i\\sin n\\theta)" },
      { name: "Principal Square Root", latex: "\\sqrt{z} = \\sqrt{r}\\left(\\cos\\frac{\\theta}{2} + i\\sin\\frac{\\theta}{2}\\right)" },
    ],
  },
  {
    key: "shapes",
    navLabel: "Shapes",
    title: "Geometry & Shape Formulas",
    description: "Area and perimeter formulas used in the Shapes calculator.",
    formulas: [
      { name: "Circle — Area", latex: "A = \\pi r^2" },
      { name: "Circle — Circumference", latex: "C = 2\\pi r" },
      { name: "Rectangle — Area", latex: "A = l\\times w" },
      { name: "Rectangle — Perimeter", latex: "P = 2(l+w)" },
      { name: "Square — Area", latex: "A = s^2" },
      { name: "Square — Perimeter", latex: "P = 4s" },
      { name: "Triangle — Area (Base × Height)", latex: "A = \\frac{1}{2}bh" },
      { name: "Triangle — Area (Heron's Formula)", latex: "A = \\sqrt{s(s-a)(s-b)(s-c)}", note: "$s = \\frac{a+b+c}{2}$" },
      { name: "Triangle — Perimeter", latex: "P = a+b+c" },
      { name: "Trapezoid — Area", latex: "A = \\frac{1}{2}(a+b)h" },
      { name: "Parallelogram — Area", latex: "A = b\\times h" },
      { name: "Ellipse — Area", latex: "A = \\pi a b" },
      { name: "Ellipse — Perimeter (Ramanujan's Approximation)", latex: "P \\approx \\pi\\left[3(a+b) - \\sqrt{(3a+b)(a+3b)}\\right]" },
      { name: "Rhombus — Area", latex: "A = \\frac{1}{2}d_1 d_2" },
      { name: "Rhombus — Side Length", latex: "s = \\sqrt{\\left(\\frac{d_1}{2}\\right)^2 + \\left(\\frac{d_2}{2}\\right)^2}" },
      { name: "Circle Sector — Area", latex: "A = \\frac{1}{2}r^2\\theta", note: "$\\theta$ in radians" },
      { name: "Arc Length", latex: "s = r\\theta" },
      { name: "Ring (Annulus) — Area", latex: "A = \\pi(R^2 - r^2)" },
      { name: "Pythagorean Theorem", latex: "a^2 + b^2 = c^2" },
    ],
  },
  {
    key: "numtheory",
    navLabel: "Number Theory",
    title: "Number Theory Formulas",
    description: "GCD, LCM, and divisor formulas used in the Number Theory calculator.",
    formulas: [
      { name: "GCD–LCM Relationship", latex: "\\gcd(a,b)\\times \\text{lcm}(a,b) = |a\\times b|" },
      { name: "LCM from GCD", latex: "\\text{lcm}(a,b) = \\frac{|a\\times b|}{\\gcd(a,b)}" },
      { name: "Euclidean Algorithm Step", latex: "\\gcd(a,b) = \\gcd(b, a \\bmod b)" },
      { name: "Base Case of Euclidean Algorithm", latex: "\\gcd(a,0) = a" },
      { name: "Prime Factorization", latex: "n = p_1^{e_1}\\times p_2^{e_2}\\times \\cdots \\times p_k^{e_k}" },
      { name: "Number of Divisors", latex: "\\tau(n) = (e_1+1)(e_2+1)\\cdots(e_k+1)" },
      { name: "Coprime Definition", latex: "\\gcd(a,b) = 1 \\iff a, b \\text{ are coprime}" },
      { name: "Divisibility Definition", latex: "a \\mid b \\iff b = ka \\text{ for some integer } k" },
      { name: "Even/Odd Test", latex: "n \\text{ is even} \\iff n \\bmod 2 = 0" },
    ],
  },
  {
    key: "numsystems",
    navLabel: "Number Systems",
    title: "Number System Formulas",
    description: "Base conversion and place-value formulas used in the Number Systems calculator.",
    formulas: [
      { name: "Place-Value Expansion", latex: "(d_n d_{n-1}\\cdots d_1 d_0)_b = \\sum_{i=0}^{n} d_i\\times b^i" },
      { name: "Binary Digit Range", latex: "\\text{base } 2:\\ d_i \\in \\{0,1\\}" },
      { name: "Octal Digit Range", latex: "\\text{base } 8:\\ d_i \\in \\{0,1,\\dots,7\\}" },
      { name: "Decimal Digit Range", latex: "\\text{base }10:\\ d_i \\in \\{0,1,\\dots,9\\}" },
      { name: "Hexadecimal Digit Range", latex: "\\text{base }16:\\ d_i \\in \\{0,\\dots,9,A,\\dots,F\\}" },
      { name: "Decimal → Base b (Division Method)", latex: "n = q_1\\times b + r_1,\\quad q_1 = q_2\\times b + r_2,\\ \\ldots" },
      { name: "Division Arithmetic (Same Base)", latex: "a \\div b = q \\text{ remainder } r" },
      { name: "Bits per Hex Digit", latex: "1 \\text{ hex digit} = 4 \\text{ binary digits (bits)}" },
      { name: "Bits per Octal Digit", latex: "1 \\text{ octal digit} = 3 \\text{ binary digits (bits)}" },
    ],
  },
  {
    key: "trig",
    navLabel: "Trigonometry",
    title: "Trigonometry Formulas",
    description: "Core identities used throughout the Trigonometry calculator.",
    formulas: [
      { name: "Pythagorean Identity", latex: "\\sin^2\\theta + \\cos^2\\theta = 1" },
      { name: "Pythagorean (Tangent Form)", latex: "1 + \\tan^2\\theta = \\sec^2\\theta" },
      { name: "Pythagorean (Cotangent Form)", latex: "1 + \\cot^2\\theta = \\csc^2\\theta" },
      { name: "Tangent Identity", latex: "\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}" },
      { name: "Cotangent Identity", latex: "\\cot\\theta = \\frac{\\cos\\theta}{\\sin\\theta}" },
      { name: "Reciprocal — Secant", latex: "\\sec\\theta = \\frac{1}{\\cos\\theta}" },
      { name: "Reciprocal — Cosecant", latex: "\\csc\\theta = \\frac{1}{\\sin\\theta}" },
      { name: "Reciprocal — Cotangent", latex: "\\cot\\theta = \\frac{1}{\\tan\\theta}" },
      { name: "Even/Odd — Cosine", latex: "\\cos(-\\theta) = \\cos\\theta" },
      { name: "Even/Odd — Sine", latex: "\\sin(-\\theta) = -\\sin\\theta" },
      { name: "Even/Odd — Tangent", latex: "\\tan(-\\theta) = -\\tan\\theta" },
      { name: "Cofunction — Sine/Cosine", latex: "\\sin\\left(\\frac{\\pi}{2}-\\theta\\right) = \\cos\\theta" },
      { name: "Cofunction — Tangent/Cotangent", latex: "\\tan\\left(\\frac{\\pi}{2}-\\theta\\right) = \\cot\\theta" },
      { name: "Sine Sum Formula", latex: "\\sin(A + B) = \\sin A\\cos B + \\cos A\\sin B" },
      { name: "Sine Difference Formula", latex: "\\sin(A - B) = \\sin A\\cos B - \\cos A\\sin B" },
      { name: "Cosine Sum Formula", latex: "\\cos(A + B) = \\cos A\\cos B - \\sin A\\sin B" },
      { name: "Cosine Difference Formula", latex: "\\cos(A - B) = \\cos A\\cos B + \\sin A\\sin B" },
      { name: "Tangent Sum Formula", latex: "\\tan(A+B) = \\frac{\\tan A + \\tan B}{1-\\tan A\\tan B}" },
      { name: "Tangent Difference Formula", latex: "\\tan(A-B) = \\frac{\\tan A - \\tan B}{1+\\tan A\\tan B}" },
      { name: "Double Angle — Sine", latex: "\\sin 2\\theta = 2\\sin\\theta\\cos\\theta" },
      { name: "Double Angle — Cosine (I)", latex: "\\cos 2\\theta = \\cos^2\\theta - \\sin^2\\theta" },
      { name: "Double Angle — Cosine (II)", latex: "\\cos 2\\theta = 2\\cos^2\\theta - 1" },
      { name: "Double Angle — Cosine (III)", latex: "\\cos 2\\theta = 1 - 2\\sin^2\\theta" },
      { name: "Double Angle — Tangent", latex: "\\tan 2\\theta = \\frac{2\\tan\\theta}{1-\\tan^2\\theta}" },
      { name: "Half Angle — Sine", latex: "\\sin\\frac{\\theta}{2} = \\pm\\sqrt{\\frac{1-\\cos\\theta}{2}}" },
      { name: "Half Angle — Cosine", latex: "\\cos\\frac{\\theta}{2} = \\pm\\sqrt{\\frac{1+\\cos\\theta}{2}}" },
      { name: "Half Angle — Tangent", latex: "\\tan\\frac{\\theta}{2} = \\frac{1-\\cos\\theta}{\\sin\\theta} = \\frac{\\sin\\theta}{1+\\cos\\theta}" },
      { name: "Product-to-Sum — Sine·Cosine", latex: "\\sin A\\cos B = \\frac{1}{2}[\\sin(A+B) + \\sin(A-B)]" },
      { name: "Product-to-Sum — Cosine·Cosine", latex: "\\cos A\\cos B = \\frac{1}{2}[\\cos(A-B) + \\cos(A+B)]" },
      { name: "Product-to-Sum — Sine·Sine", latex: "\\sin A\\sin B = \\frac{1}{2}[\\cos(A-B) - \\cos(A+B)]" },
      { name: "Sum-to-Product — Sine + Sine", latex: "\\sin A + \\sin B = 2\\sin\\left(\\frac{A+B}{2}\\right)\\cos\\left(\\frac{A-B}{2}\\right)" },
      { name: "Sum-to-Product — Cosine + Cosine", latex: "\\cos A + \\cos B = 2\\cos\\left(\\frac{A+B}{2}\\right)\\cos\\left(\\frac{A-B}{2}\\right)" },
      { name: "Law of Sines", latex: "\\frac{a}{\\sin A} = \\frac{b}{\\sin B} = \\frac{c}{\\sin C}" },
      { name: "Law of Cosines", latex: "c^2 = a^2 + b^2 - 2ab\\cos C" },
      { name: "Area of a Triangle (SAS)", latex: "A = \\frac{1}{2}ab\\sin C" },
      { name: "SOH-CAH-TOA", latex: "\\sin\\theta = \\frac{\\text{opp}}{\\text{hyp}},\\ \\cos\\theta = \\frac{\\text{adj}}{\\text{hyp}},\\ \\tan\\theta = \\frac{\\text{opp}}{\\text{adj}}" },
      { name: "Radians ↔ Degrees", latex: "\\text{radians} = \\text{degrees}\\times \\frac{\\pi}{180}" },
      { name: "Period — Sine & Cosine", latex: "\\sin(\\theta + 2\\pi) = \\sin\\theta,\\quad \\cos(\\theta+2\\pi)=\\cos\\theta" },
      { name: "Period — Tangent", latex: "\\tan(\\theta+\\pi) = \\tan\\theta" },
    ],
  },
];
