import katex from "katex";
import type { FormulaTopic } from "./formula-sheet-data";

/**
 * Deliberately hardcoded palette (not the app's live CSS variables): the
 * app's theme is built on oklch() colors, which html2canvas cannot parse
 * ("Attempting to parse an unsupported color function 'oklch'") — so the
 * export renders its own fixed, Calculin-styled palette instead of trying
 * to snapshot whatever theme/accent the person currently has active. This
 * also keeps exported PDFs consistently light/print-friendly regardless of
 * whether the on-screen app is in dark mode.
 */
const PDF_COLORS = {
  bg: "#ffffff",
  headerFrom: "#4f46e5",
  headerTo: "#7c3aed",
  headerText: "#ffffff",
  headerSubtext: "#e0d9fb",
  text: "#1e1b2e",
  muted: "#6b6580",
  cardBg: "#f8f7fc",
  cardBorder: "#e6e2f2",
  accentBar: "#7c3aed",
  footerText: "#a39cc0",
};

function formatGeneratedDate(): string {
  return new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
}

/** Renders a note string that may contain inline `$...$` math segments,
 *  e.g. "for $n \neq -1$", as a mix of plain text and inline KaTeX HTML. */
function renderNoteHTML(note: string): string {
  return note.replace(/\$([^$]+)\$/g, (_match, inner: string) =>
    katex.renderToString(inner, { throwOnError: false, strict: "ignore" })
  );
}

function buildExportHTML(topic: FormulaTopic): string {
  const cards = topic.formulas
    .map((f) => {
      const katexHtml = katex.renderToString(f.latex, { displayMode: true, throwOnError: false, strict: "ignore" });
      return `
        <div style="background:${PDF_COLORS.cardBg}; border:1px solid ${PDF_COLORS.cardBorder}; border-left:4px solid ${PDF_COLORS.accentBar}; border-radius:10px; padding:14px 16px; break-inside:avoid;">
          <div style="font-size:13px; font-weight:600; color:${PDF_COLORS.text}; margin-bottom:6px;">${f.name}</div>
          <div style="font-size:16px; color:${PDF_COLORS.text}; overflow-x:auto;">${katexHtml}</div>
          ${f.note ? `<div style="font-size:11px; color:${PDF_COLORS.muted}; margin-top:6px;">${renderNoteHTML(f.note)}</div>` : ""}
        </div>`;
    })
    .join("\n");

  return `
    <div style="width:820px; font-family: 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; background:${PDF_COLORS.bg}; color:${PDF_COLORS.text};">
      <div style="background:linear-gradient(135deg, ${PDF_COLORS.headerFrom}, ${PDF_COLORS.headerTo}); padding:36px 40px 28px; color:${PDF_COLORS.headerText};">
        <div style="display:flex; align-items:center; gap:10px; margin-bottom:18px;">
          <div style="width:34px; height:34px; border-radius:10px; background:rgba(255,255,255,0.18); display:flex; align-items:center; justify-content:center; font-weight:700; font-size:18px;">&int;</div>
          <div style="font-size:18px; font-weight:700; letter-spacing:0.02em;">Calculin</div>
        </div>
        <div style="font-size:30px; font-weight:800; margin-bottom:8px;">${topic.title}</div>
        <div style="font-size:14px; color:${PDF_COLORS.headerSubtext};">${topic.description}</div>
      </div>
      <div style="padding:28px 40px 8px; display:grid; grid-template-columns:1fr 1fr; gap:14px;">
        ${cards}
      </div>
      <div style="padding:20px 40px 32px; display:flex; justify-content:space-between; align-items:center; font-size:11px; color:${PDF_COLORS.footerText}; border-top:1px solid ${PDF_COLORS.cardBorder}; margin-top:12px;">
        <span>Generated by Calculin — calculin.vercel.app</span>
        <span>${formatGeneratedDate()}</span>
      </div>
    </div>`;
}

export async function exportFormulaSheetPDF(topic: FormulaTopic): Promise<void> {
  const [{ default: html2canvas }, { jsPDF }] = await Promise.all([
    import("html2canvas"),
    import("jspdf"),
  ]);

  const container = document.createElement("div");
  container.style.position = "absolute";
  container.style.top = "0";
  container.style.left = "-99999px";
  container.style.zIndex = "-1";
  container.style.pointerEvents = "none";
  container.innerHTML = buildExportHTML(topic);
  document.body.appendChild(container);

  try {
    // Let the browser lay out/paint the injected KaTeX markup (and load its
    // web fonts) before capture.
    await new Promise((resolve) => setTimeout(resolve, 150));

    const captureOptions = {
      scale: 2,
      backgroundColor: PDF_COLORS.bg,
      useCORS: true,
      logging: false,
    };

    let canvas: HTMLCanvasElement;
    try {
      // The app's global stylesheet sets `* { border-color: oklch(...) }`
      // and `body { background-color: oklch(...) }` — html2canvas's default
      // rendering path parses every element's computed CSS color values
      // itself and throws on oklch() ("Attempting to parse an unsupported
      // color function 'oklch'") the moment it walks past this hidden
      // container to the rest of the (oklch-themed) live app in the DOM.
      // foreignObjectRendering hands the actual pixel rendering to the
      // browser's native SVG/paint engine instead — which *does* understand
      // oklch() — sidestepping that crash entirely rather than needing to
      // rewrite the whole app's color system just for PDF export.
      canvas = await html2canvas(container, { ...captureOptions, foreignObjectRendering: true });
    } catch {
      // Fall back to html2canvas's default (non-SVG) rendering path in case
      // foreignObjectRendering itself hits a browser-specific limitation —
      // still works for most content, just via the older code path.
      canvas = await html2canvas(container, { ...captureOptions, foreignObjectRendering: false });
    }

    const pdf = new jsPDF("p", "pt", "a4");
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pageWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    const imgData = canvas.toDataURL("image/png");

    let heightLeft = imgHeight;
    let position = 0;
    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(`Calculin-${topic.key}-formula-sheet.pdf`);
  } finally {
    document.body.removeChild(container);
  }
}
