import type { FormulaTopic } from "./formula-sheet-data";
import { latexToPlainText } from "./latex-to-text";

// A deliberately fixed palette (not the app's live oklch-based theme
// variables) so the PDF always looks the same regardless of which
// dark/light/accent theme is active on screen — colors as [R, G, B] 0-255
// triples, since jsPDF's setFillColor/setTextColor take plain RGB.
const COLORS = {
  headerFrom: [79, 70, 229] as [number, number, number], // indigo-600
  headerTo: [124, 58, 237] as [number, number, number], // violet-600
  headerText: [255, 255, 255] as [number, number, number],
  headerSubtext: [224, 217, 251] as [number, number, number],
  text: [30, 27, 46] as [number, number, number],
  muted: [107, 101, 128] as [number, number, number],
  cardBg: [248, 247, 252] as [number, number, number],
  cardBorder: [230, 226, 242] as [number, number, number],
  accentBar: [124, 58, 237] as [number, number, number],
  footerText: [163, 156, 192] as [number, number, number],
};

function formatGeneratedDate(): string {
  return new Date().toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
}

/**
 * Draws a formula topic straight to jsPDF using its native text/shape API —
 * no DOM screenshot at all. The previous html2canvas-based approach tried
 * to rasterize dozens of fully-rendered KaTeX formulas (each one hundreds
 * of nested DOM nodes) in a single pass, which could hang the tab for a
 * long time (or indefinitely) on slower devices. This is slower to author
 * but fast and reliable to run: pure vector/text drawing, nothing to wait
 * on, nothing that can freeze the page.
 */
export async function exportFormulaSheetPDF(topic: FormulaTopic): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF("p", "pt", "a4");

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 40;
  const gutter = 16;
  const colWidth = (pageWidth - margin * 2 - gutter) / 2;
  const footerHeight = 34;
  const contentBottom = pageHeight - footerHeight - 16;

  let page = 1;

  const drawFooter = () => {
    pdf.setDrawColor(...COLORS.cardBorder);
    pdf.line(margin, pageHeight - footerHeight, pageWidth - margin, pageHeight - footerHeight);
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...COLORS.footerText);
    pdf.text("Generated by Calculin \u2014 calculin.vercel.app", margin, pageHeight - footerHeight + 16);
    pdf.text(`${formatGeneratedDate()} \u00b7 Page ${page}`, pageWidth - margin, pageHeight - footerHeight + 16, { align: "right" });
  };

  const drawHeaderBand = (compact: boolean): number => {
    const bandHeight = compact ? 56 : 128;
    // Fake a gradient with a handful of horizontal color-interpolated
    // strips — jsPDF has no native linear-gradient fill.
    const steps = 24;
    for (let i = 0; i < steps; i++) {
      const t = i / (steps - 1);
      const r = Math.round(COLORS.headerFrom[0] + (COLORS.headerTo[0] - COLORS.headerFrom[0]) * t);
      const g = Math.round(COLORS.headerFrom[1] + (COLORS.headerTo[1] - COLORS.headerFrom[1]) * t);
      const b = Math.round(COLORS.headerFrom[2] + (COLORS.headerTo[2] - COLORS.headerFrom[2]) * t);
      pdf.setFillColor(r, g, b);
      const stripW = pageWidth / steps;
      pdf.rect(i * stripW, 0, stripW + 1, bandHeight, "F");
    }

    pdf.setFillColor(255, 255, 255);
    pdf.roundedRect(margin, compact ? 14 : 28, 26, 26, 6, 6, "F");
    pdf.setTextColor(...COLORS.headerFrom);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);
    pdf.text("\u222b", margin + 13, compact ? 32 : 46, { align: "center" });

    pdf.setTextColor(...COLORS.headerText);
    pdf.setFontSize(13);
    pdf.text("Calculin", margin + 34, compact ? 31 : 45);

    if (!compact) {
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(24);
      pdf.text(topic.title, margin, 82);

      pdf.setFont("helvetica", "normal");
      pdf.setFontSize(11);
      pdf.setTextColor(...COLORS.headerSubtext);
      const descLines = pdf.splitTextToSize(topic.description, pageWidth - margin * 2);
      pdf.text(descLines, margin, 104);
    } else {
      pdf.setFont("helvetica", "bold");
      pdf.setFontSize(12);
      pdf.text(topic.title, pageWidth - margin, 34, { align: "right" });
    }

    return bandHeight;
  };

  const startNewPage = () => {
    pdf.addPage();
    page++;
    const bandHeight = drawHeaderBand(true);
    drawFooter();
    return bandHeight + 20;
  };

  let y = drawHeaderBand(false) + 30;
  drawFooter();

  let leftColHeight = 0;

  topic.formulas.forEach((f, i) => {
    const col = i % 2;
    const x = margin + col * (colWidth + gutter);

    const plain = latexToPlainText(f.latex);
    pdf.setFont("courier", "normal");
    pdf.setFontSize(10.5);
    const formulaLines: string[] = pdf.splitTextToSize(plain, colWidth - 24);

    pdf.setFont("helvetica", "italic");
    pdf.setFontSize(8);
    const noteLines: string[] = f.note ? pdf.splitTextToSize(latexToPlainText(f.note), colWidth - 24) : [];

    const nameHeight = 16;
    const formulaHeight = formulaLines.length * 13;
    const noteHeight = noteLines.length ? noteLines.length * 10 + 6 : 0;
    const cardHeight = nameHeight + formulaHeight + noteHeight + 18;

    // Only ever break pages at the start of a left column, so a page
    // always ends on a clean row boundary rather than mid-row.
    if (col === 0 && y + cardHeight > contentBottom) {
      y = startNewPage();
    }

    pdf.setFillColor(...COLORS.cardBg);
    pdf.setDrawColor(...COLORS.cardBorder);
    pdf.roundedRect(x, y, colWidth, cardHeight, 4, 4, "FD");
    pdf.setFillColor(...COLORS.accentBar);
    pdf.rect(x, y, 3, cardHeight, "F");

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(9.5);
    pdf.setTextColor(...COLORS.text);
    pdf.text(f.name, x + 12, y + 15);

    pdf.setFont("courier", "normal");
    pdf.setFontSize(10.5);
    pdf.setTextColor(...COLORS.text);
    pdf.text(formulaLines, x + 12, y + 15 + 15);

    if (noteLines.length) {
      pdf.setFont("helvetica", "italic");
      pdf.setFontSize(8);
      pdf.setTextColor(...COLORS.muted);
      pdf.text(noteLines, x + 12, y + 15 + formulaHeight + 16);
    }

    if (col === 0) {
      leftColHeight = cardHeight;
    }
    // Advance y once per row (after the right column, or after a lone
    // last left-column card), using the taller of the pair so rows never
    // overlap.
    const isLastFormula = i === topic.formulas.length - 1;
    if (col === 1 || isLastFormula) {
      const rowHeight = col === 1 ? Math.max(leftColHeight, cardHeight) : cardHeight;
      y += rowHeight + 12;
    }
  });

  pdf.save(`Calculin-${topic.key}-formula-sheet.pdf`);
}
